// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package com.nmt.payapi;

import com.sun.xml.rpc.encoding.DeserializationException;
import com.sun.xml.rpc.encoding.SOAPInstanceBuilder;
import static com.sun.xml.rpc.encoding.SOAPInstanceBuilder.GATES_INITIALIZATION;
import static com.sun.xml.rpc.encoding.SOAPInstanceBuilder.REQUIRES_CREATION;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class TCallMeResult_SOAPBuilder implements SOAPInstanceBuilder {

  private com.nmt.payapi.TCallMeResult _instance;
  private java.lang.String messageCode;
  private java.lang.String messageDescription;
  private static final int myMESSAGECODE_INDEX = 0;
  private static final int myMESSAGEDESCRIPTION_INDEX = 1;

  public TCallMeResult_SOAPBuilder() {
  }

  public void setMessageCode(java.lang.String messageCode) {
    this.messageCode = messageCode;
  }

  public void setMessageDescription(java.lang.String messageDescription) {
    this.messageDescription = messageDescription;
  }

  public int memberGateType(int memberIndex) {
    switch (memberIndex) {
      case myMESSAGECODE_INDEX:
        return GATES_INITIALIZATION | REQUIRES_CREATION;
      case myMESSAGEDESCRIPTION_INDEX:
        return GATES_INITIALIZATION | REQUIRES_CREATION;
      default:
        throw new IllegalArgumentException();
    }
  }

  public void construct() {
  }

  public void setMember(int index, java.lang.Object memberValue) {
    try {
      switch (index) {
        case myMESSAGECODE_INDEX:
          _instance.setMessageCode((java.lang.String) memberValue);
          break;
        case myMESSAGEDESCRIPTION_INDEX:
          _instance.setMessageDescription((java.lang.String) memberValue);
          break;
        default:
          throw new java.lang.IllegalArgumentException();
      }
    } catch (java.lang.RuntimeException e) {
      throw e;
    } catch (java.lang.Exception e) {
      throw new DeserializationException(new LocalizableExceptionAdapter(e));
    }
  }

  public void initialize() {
  }

  public void setInstance(java.lang.Object instance) {
    _instance = (com.nmt.payapi.TCallMeResult) instance;
  }

  public java.lang.Object getInstance() {
    return _instance;
  }
}
