// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;


public class TCancelPolicy {
    protected java.lang.String messageCode;
    protected java.lang.String messageDescription;
    
    public TCancelPolicy() {
    }
    
    public TCancelPolicy(java.lang.String messageCode, java.lang.String messageDescription) {
        this.messageCode = messageCode;
        this.messageDescription = messageDescription;
    }
    
    public java.lang.String getMessageCode() {
        return messageCode;
    }
    
    public void setMessageCode(java.lang.String messageCode) {
        this.messageCode = messageCode;
    }
    
    public java.lang.String getMessageDescription() {
        return messageDescription;
    }
    
    public void setMessageDescription(java.lang.String messageDescription) {
        this.messageDescription = messageDescription;
    }
}
