// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class TClientDetailAccArray_SOAPBuilder implements SOAPInstanceBuilder {
    private com.nmt.payapi.TClientDetailAccArray _instance;
    private java.lang.String additionalField1;
    private java.lang.String additionalField2;
    private java.lang.String additionalField3;
    private java.lang.String additionalField4;
    private java.lang.String additionalField5;
    private java.lang.String additionalField6;
    private java.lang.String additionalField7;
    private java.lang.String additionalField8;
    private java.lang.String additionalField9;
    private java.lang.String additionalField10;
    private java.lang.String additionalField11;
    private java.lang.String additionalField12;
    private java.lang.String additionalField13;
    private java.lang.String additionalField14;
    private java.lang.String additionalField15;
    private java.lang.String additionalField16;
    private java.lang.String additionalField17;
    private java.lang.String additionalField18;
    private java.lang.String additionalField19;
    private java.lang.String additionalField20;
    private com.nmt.payapi.TClientDetailAccSubArray[] subDetail;
    private static final int myADDITIONALFIELD1_INDEX = 0;
    private static final int myADDITIONALFIELD2_INDEX = 1;
    private static final int myADDITIONALFIELD3_INDEX = 2;
    private static final int myADDITIONALFIELD4_INDEX = 3;
    private static final int myADDITIONALFIELD5_INDEX = 4;
    private static final int myADDITIONALFIELD6_INDEX = 5;
    private static final int myADDITIONALFIELD7_INDEX = 6;
    private static final int myADDITIONALFIELD8_INDEX = 7;
    private static final int myADDITIONALFIELD9_INDEX = 8;
    private static final int myADDITIONALFIELD10_INDEX = 9;
    private static final int myADDITIONALFIELD11_INDEX = 10;
    private static final int myADDITIONALFIELD12_INDEX = 11;
    private static final int myADDITIONALFIELD13_INDEX = 12;
    private static final int myADDITIONALFIELD14_INDEX = 13;
    private static final int myADDITIONALFIELD15_INDEX = 14;
    private static final int myADDITIONALFIELD16_INDEX = 15;
    private static final int myADDITIONALFIELD17_INDEX = 16;
    private static final int myADDITIONALFIELD18_INDEX = 17;
    private static final int myADDITIONALFIELD19_INDEX = 18;
    private static final int myADDITIONALFIELD20_INDEX = 19;
    private static final int mySUBDETAIL_INDEX = 20;
    
    public TClientDetailAccArray_SOAPBuilder() {
    }
    
    public void setAdditionalField1(java.lang.String additionalField1) {
        this.additionalField1 = additionalField1;
    }
    
    public void setAdditionalField2(java.lang.String additionalField2) {
        this.additionalField2 = additionalField2;
    }
    
    public void setAdditionalField3(java.lang.String additionalField3) {
        this.additionalField3 = additionalField3;
    }
    
    public void setAdditionalField4(java.lang.String additionalField4) {
        this.additionalField4 = additionalField4;
    }
    
    public void setAdditionalField5(java.lang.String additionalField5) {
        this.additionalField5 = additionalField5;
    }
    
    public void setAdditionalField6(java.lang.String additionalField6) {
        this.additionalField6 = additionalField6;
    }
    
    public void setAdditionalField7(java.lang.String additionalField7) {
        this.additionalField7 = additionalField7;
    }
    
    public void setAdditionalField8(java.lang.String additionalField8) {
        this.additionalField8 = additionalField8;
    }
    
    public void setAdditionalField9(java.lang.String additionalField9) {
        this.additionalField9 = additionalField9;
    }
    
    public void setAdditionalField10(java.lang.String additionalField10) {
        this.additionalField10 = additionalField10;
    }
    
    public void setAdditionalField11(java.lang.String additionalField11) {
        this.additionalField11 = additionalField11;
    }
    
    public void setAdditionalField12(java.lang.String additionalField12) {
        this.additionalField12 = additionalField12;
    }
    
    public void setAdditionalField13(java.lang.String additionalField13) {
        this.additionalField13 = additionalField13;
    }
    
    public void setAdditionalField14(java.lang.String additionalField14) {
        this.additionalField14 = additionalField14;
    }
    
    public void setAdditionalField15(java.lang.String additionalField15) {
        this.additionalField15 = additionalField15;
    }
    
    public void setAdditionalField16(java.lang.String additionalField16) {
        this.additionalField16 = additionalField16;
    }
    
    public void setAdditionalField17(java.lang.String additionalField17) {
        this.additionalField17 = additionalField17;
    }
    
    public void setAdditionalField18(java.lang.String additionalField18) {
        this.additionalField18 = additionalField18;
    }
    
    public void setAdditionalField19(java.lang.String additionalField19) {
        this.additionalField19 = additionalField19;
    }
    
    public void setAdditionalField20(java.lang.String additionalField20) {
        this.additionalField20 = additionalField20;
    }
    
    public void setSubDetail(com.nmt.payapi.TClientDetailAccSubArray[] subDetail) {
        this.subDetail = subDetail;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myADDITIONALFIELD1_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD2_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD3_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD4_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD5_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD6_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD7_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD8_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD9_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD10_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD11_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD12_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD13_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD14_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD15_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD16_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD17_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD18_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD19_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD20_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySUBDETAIL_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myADDITIONALFIELD1_INDEX:
                    _instance.setAdditionalField1((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD2_INDEX:
                    _instance.setAdditionalField2((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD3_INDEX:
                    _instance.setAdditionalField3((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD4_INDEX:
                    _instance.setAdditionalField4((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD5_INDEX:
                    _instance.setAdditionalField5((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD6_INDEX:
                    _instance.setAdditionalField6((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD7_INDEX:
                    _instance.setAdditionalField7((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD8_INDEX:
                    _instance.setAdditionalField8((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD9_INDEX:
                    _instance.setAdditionalField9((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD10_INDEX:
                    _instance.setAdditionalField10((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD11_INDEX:
                    _instance.setAdditionalField11((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD12_INDEX:
                    _instance.setAdditionalField12((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD13_INDEX:
                    _instance.setAdditionalField13((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD14_INDEX:
                    _instance.setAdditionalField14((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD15_INDEX:
                    _instance.setAdditionalField15((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD16_INDEX:
                    _instance.setAdditionalField16((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD17_INDEX:
                    _instance.setAdditionalField17((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD18_INDEX:
                    _instance.setAdditionalField18((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD19_INDEX:
                    _instance.setAdditionalField19((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD20_INDEX:
                    _instance.setAdditionalField20((java.lang.String)memberValue);
                    break;
                case mySUBDETAIL_INDEX:
                    _instance.setSubDetail((com.nmt.payapi.TClientDetailAccSubArray[])memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.nmt.payapi.TClientDetailAccArray)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
