// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;


public class TClientDetailAccSubArray {
    protected java.lang.String additionalField1;
    protected java.lang.String additionalField2;
    protected java.lang.String additionalField3;
    protected java.lang.String additionalField4;
    
    public TClientDetailAccSubArray() {
    }
    
    public TClientDetailAccSubArray(java.lang.String additionalField1, java.lang.String additionalField2, java.lang.String additionalField3, java.lang.String additionalField4) {
        this.additionalField1 = additionalField1;
        this.additionalField2 = additionalField2;
        this.additionalField3 = additionalField3;
        this.additionalField4 = additionalField4;
    }
    
    public java.lang.String getAdditionalField1() {
        return additionalField1;
    }
    
    public void setAdditionalField1(java.lang.String additionalField1) {
        this.additionalField1 = additionalField1;
    }
    
    public java.lang.String getAdditionalField2() {
        return additionalField2;
    }
    
    public void setAdditionalField2(java.lang.String additionalField2) {
        this.additionalField2 = additionalField2;
    }
    
    public java.lang.String getAdditionalField3() {
        return additionalField3;
    }
    
    public void setAdditionalField3(java.lang.String additionalField3) {
        this.additionalField3 = additionalField3;
    }
    
    public java.lang.String getAdditionalField4() {
        return additionalField4;
    }
    
    public void setAdditionalField4(java.lang.String additionalField4) {
        this.additionalField4 = additionalField4;
    }
}
