// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class TClientDetailAccArray_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_AdditionalField1_QNAME = new QName("", "AdditionalField1");
    private static final javax.xml.namespace.QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer ns2_myns2_string__java_lang_String_String_Serializer;
    private static final javax.xml.namespace.QName ns1_AdditionalField2_QNAME = new QName("", "AdditionalField2");
    private static final javax.xml.namespace.QName ns1_AdditionalField3_QNAME = new QName("", "AdditionalField3");
    private static final javax.xml.namespace.QName ns1_AdditionalField4_QNAME = new QName("", "AdditionalField4");
    private static final javax.xml.namespace.QName ns1_AdditionalField5_QNAME = new QName("", "AdditionalField5");
    private static final javax.xml.namespace.QName ns1_AdditionalField6_QNAME = new QName("", "AdditionalField6");
    private static final javax.xml.namespace.QName ns1_AdditionalField7_QNAME = new QName("", "AdditionalField7");
    private static final javax.xml.namespace.QName ns1_AdditionalField8_QNAME = new QName("", "AdditionalField8");
    private static final javax.xml.namespace.QName ns1_AdditionalField9_QNAME = new QName("", "AdditionalField9");
    private static final javax.xml.namespace.QName ns1_AdditionalField10_QNAME = new QName("", "AdditionalField10");
    private static final javax.xml.namespace.QName ns1_AdditionalField11_QNAME = new QName("", "AdditionalField11");
    private static final javax.xml.namespace.QName ns1_AdditionalField12_QNAME = new QName("", "AdditionalField12");
    private static final javax.xml.namespace.QName ns1_AdditionalField13_QNAME = new QName("", "AdditionalField13");
    private static final javax.xml.namespace.QName ns1_AdditionalField14_QNAME = new QName("", "AdditionalField14");
    private static final javax.xml.namespace.QName ns1_AdditionalField15_QNAME = new QName("", "AdditionalField15");
    private static final javax.xml.namespace.QName ns1_AdditionalField16_QNAME = new QName("", "AdditionalField16");
    private static final javax.xml.namespace.QName ns1_AdditionalField17_QNAME = new QName("", "AdditionalField17");
    private static final javax.xml.namespace.QName ns1_AdditionalField18_QNAME = new QName("", "AdditionalField18");
    private static final javax.xml.namespace.QName ns1_AdditionalField19_QNAME = new QName("", "AdditionalField19");
    private static final javax.xml.namespace.QName ns1_AdditionalField20_QNAME = new QName("", "AdditionalField20");
    private static final javax.xml.namespace.QName ns1_SubDetail_QNAME = new QName("", "SubDetail");
    private static final javax.xml.namespace.QName ns3_SubArrayOfClientDetailAcc_TYPE_QNAME = new QName("urn:WebserviceIntf", "SubArrayOfClientDetailAcc");
    private CombinedSerializer ns3_myns3_SubArrayOfClientDetailAcc__TClientDetailAccSubArrayArray_SOAPSerializer1;
    private static final int myADDITIONALFIELD1_INDEX = 0;
    private static final int myADDITIONALFIELD2_INDEX = 1;
    private static final int myADDITIONALFIELD3_INDEX = 2;
    private static final int myADDITIONALFIELD4_INDEX = 3;
    private static final int myADDITIONALFIELD5_INDEX = 4;
    private static final int myADDITIONALFIELD6_INDEX = 5;
    private static final int myADDITIONALFIELD7_INDEX = 6;
    private static final int myADDITIONALFIELD8_INDEX = 7;
    private static final int myADDITIONALFIELD9_INDEX = 8;
    private static final int myADDITIONALFIELD10_INDEX = 9;
    private static final int myADDITIONALFIELD11_INDEX = 10;
    private static final int myADDITIONALFIELD12_INDEX = 11;
    private static final int myADDITIONALFIELD13_INDEX = 12;
    private static final int myADDITIONALFIELD14_INDEX = 13;
    private static final int myADDITIONALFIELD15_INDEX = 14;
    private static final int myADDITIONALFIELD16_INDEX = 15;
    private static final int myADDITIONALFIELD17_INDEX = 16;
    private static final int myADDITIONALFIELD18_INDEX = 17;
    private static final int myADDITIONALFIELD19_INDEX = 18;
    private static final int myADDITIONALFIELD20_INDEX = 19;
    private static final int mySUBDETAIL_INDEX = 20;
    
    public TClientDetailAccArray_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws java.lang.Exception {
        ns2_myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, java.lang.String.class, ns2_string_TYPE_QNAME);
        ns3_myns3_SubArrayOfClientDetailAcc__TClientDetailAccSubArrayArray_SOAPSerializer1 = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.nmt.payapi.TClientDetailAccSubArray[].class, ns3_SubArrayOfClientDetailAcc_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        com.nmt.payapi.TClientDetailAccArray instance = new com.nmt.payapi.TClientDetailAccArray();
        com.nmt.payapi.TClientDetailAccArray_SOAPBuilder builder = null;
        java.lang.Object member;
        boolean isComplete = true;
        javax.xml.namespace.QName elementName;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField1_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField1_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD1_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField1((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField2_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField2_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD2_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField2((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField3_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField3_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD3_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField3((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField4_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField4_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD4_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField4((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField5_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField5_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD5_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField5((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField6_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField6_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD6_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField6((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField7_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField7_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD7_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField7((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField8_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField8_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD8_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField8((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField9_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField9_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD9_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField9((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField10_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField10_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD10_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField10((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField11_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField11_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD11_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField11((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField12_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField12_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD12_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField12((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField13_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField13_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD13_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField13((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField14_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField14_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD14_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField14((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField15_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField15_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD15_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField15((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField16_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField16_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD16_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField16((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField17_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField17_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD17_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField17((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField18_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField18_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD18_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField18((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField19_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField19_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD19_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField19((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalField20_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AdditionalField20_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDITIONALFIELD20_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAdditionalField20((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SubDetail_QNAME)) {
                member = ns3_myns3_SubArrayOfClientDetailAcc__TClientDetailAccSubArrayArray_SOAPSerializer1.deserialize(ns1_SubDetail_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailAccArray_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, mySUBDETAIL_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setSubDetail((com.nmt.payapi.TClientDetailAccSubArray[])member);
                }
                reader.nextElementContent();
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (java.lang.Object)instance : (java.lang.Object)state);
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.nmt.payapi.TClientDetailAccArray instance = (com.nmt.payapi.TClientDetailAccArray)obj;
        
    }
    
    public void doSerializeInstance(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.nmt.payapi.TClientDetailAccArray instance = (com.nmt.payapi.TClientDetailAccArray)obj;
        
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField1(), ns1_AdditionalField1_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField2(), ns1_AdditionalField2_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField3(), ns1_AdditionalField3_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField4(), ns1_AdditionalField4_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField5(), ns1_AdditionalField5_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField6(), ns1_AdditionalField6_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField7(), ns1_AdditionalField7_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField8(), ns1_AdditionalField8_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField9(), ns1_AdditionalField9_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField10(), ns1_AdditionalField10_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField11(), ns1_AdditionalField11_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField12(), ns1_AdditionalField12_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField13(), ns1_AdditionalField13_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField14(), ns1_AdditionalField14_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField15(), ns1_AdditionalField15_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField16(), ns1_AdditionalField16_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField17(), ns1_AdditionalField17_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField18(), ns1_AdditionalField18_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField19(), ns1_AdditionalField19_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAdditionalField20(), ns1_AdditionalField20_QNAME, null, writer, context);
        ns3_myns3_SubArrayOfClientDetailAcc__TClientDetailAccSubArrayArray_SOAPSerializer1.serialize(instance.getSubDetail(), ns1_SubDetail_QNAME, null, writer, context);
    }
}
