// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class TClientDetailAccSubArray_SOAPBuilder implements SOAPInstanceBuilder {
    private com.nmt.payapi.TClientDetailAccSubArray _instance;
    private java.lang.String additionalField1;
    private java.lang.String additionalField2;
    private java.lang.String additionalField3;
    private java.lang.String additionalField4;
    private static final int myADDITIONALFIELD1_INDEX = 0;
    private static final int myADDITIONALFIELD2_INDEX = 1;
    private static final int myADDITIONALFIELD3_INDEX = 2;
    private static final int myADDITIONALFIELD4_INDEX = 3;
    
    public TClientDetailAccSubArray_SOAPBuilder() {
    }
    
    public void setAdditionalField1(java.lang.String additionalField1) {
        this.additionalField1 = additionalField1;
    }
    
    public void setAdditionalField2(java.lang.String additionalField2) {
        this.additionalField2 = additionalField2;
    }
    
    public void setAdditionalField3(java.lang.String additionalField3) {
        this.additionalField3 = additionalField3;
    }
    
    public void setAdditionalField4(java.lang.String additionalField4) {
        this.additionalField4 = additionalField4;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myADDITIONALFIELD1_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD2_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD3_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDITIONALFIELD4_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myADDITIONALFIELD1_INDEX:
                    _instance.setAdditionalField1((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD2_INDEX:
                    _instance.setAdditionalField2((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD3_INDEX:
                    _instance.setAdditionalField3((java.lang.String)memberValue);
                    break;
                case myADDITIONALFIELD4_INDEX:
                    _instance.setAdditionalField4((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.nmt.payapi.TClientDetailAccSubArray)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
