// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class TClientDetailPolicy_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_PaymentRefNumber_QNAME = new QName("", "PaymentRefNumber");
    private static final javax.xml.namespace.QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer ns2_myns2_string__java_lang_String_String_Serializer;
    private static final javax.xml.namespace.QName ns1_FirstName_QNAME = new QName("", "FirstName");
    private static final javax.xml.namespace.QName ns1_LastName_QNAME = new QName("", "LastName");
    private static final javax.xml.namespace.QName ns1_IDNumber_QNAME = new QName("", "IDNumber");
    private static final javax.xml.namespace.QName ns1_ContactNumber_QNAME = new QName("", "ContactNumber");
    private static final javax.xml.namespace.QName ns1_Address_QNAME = new QName("", "Address");
    private static final javax.xml.namespace.QName ns1_AmountDue_QNAME = new QName("", "AmountDue");
    private static final javax.xml.namespace.QName ns2_double_TYPE_QNAME = SchemaConstants.QNAME_TYPE_DOUBLE;
    private CombinedSerializer ns2_myns2__double__double_Double_Serializer;
    private static final javax.xml.namespace.QName ns1_AdditionalAmount_QNAME = new QName("", "AdditionalAmount");
    private static final javax.xml.namespace.QName ns1_DueDate_QNAME = new QName("", "DueDate");
    private static final javax.xml.namespace.QName ns1_Institution_QNAME = new QName("", "Institution");
    private static final javax.xml.namespace.QName ns1_InstitutionCallCenter_QNAME = new QName("", "InstitutionCallCenter");
    private static final javax.xml.namespace.QName ns1_PolicyStatus_QNAME = new QName("", "PolicyStatus");
    private static final javax.xml.namespace.QName ns1_RegistrationDate_QNAME = new QName("", "RegistrationDate");
    private static final javax.xml.namespace.QName ns1_CustomerMessage_QNAME = new QName("", "CustomerMessage");
    private static final javax.xml.namespace.QName ns1_VerifyClientDetails_QNAME = new QName("", "VerifyClientDetails");
    private static final javax.xml.namespace.QName ns1_ReceiveIDcopy_QNAME = new QName("", "ReceiveIDcopy");
    private static final javax.xml.namespace.QName ns1_AcceptPartPayment_QNAME = new QName("", "AcceptPartPayment");
    private static final javax.xml.namespace.QName ns1_AcceptAdditional_QNAME = new QName("", "AcceptAdditional");
    private static final javax.xml.namespace.QName ns1_TransactionStatus_QNAME = new QName("", "TransactionStatus");
    private static final javax.xml.namespace.QName ns1_TransactionConfirm_QNAME = new QName("", "TransactionConfirm");
    private static final javax.xml.namespace.QName ns1_MessageCode_QNAME = new QName("", "MessageCode");
    private static final javax.xml.namespace.QName ns1_MessageDescription_QNAME = new QName("", "MessageDescription");
    private static final javax.xml.namespace.QName ns1_CustomField1_QNAME = new QName("", "CustomField1");
    private static final javax.xml.namespace.QName ns1_CustomField2_QNAME = new QName("", "CustomField2");
    private static final javax.xml.namespace.QName ns1_CustomField3_QNAME = new QName("", "CustomField3");
    private static final javax.xml.namespace.QName ns1_TransactionID_QNAME = new QName("", "TransactionID");
    private static final javax.xml.namespace.QName ns1_PolicyPaid_QNAME = new QName("", "PolicyPaid");
    private static final int myPAYMENTREFNUMBER_INDEX = 0;
    private static final int myFIRSTNAME_INDEX = 1;
    private static final int myLASTNAME_INDEX = 2;
    private static final int myIDNUMBER_INDEX = 3;
    private static final int myCONTACTNUMBER_INDEX = 4;
    private static final int myADDRESS_INDEX = 5;
    private static final int myAMOUNTDUE_INDEX = 6;
    private static final int myADDITIONALAMOUNT_INDEX = 7;
    private static final int myDUEDATE_INDEX = 8;
    private static final int myINSTITUTION_INDEX = 9;
    private static final int myINSTITUTIONCALLCENTER_INDEX = 10;
    private static final int myPOLICYSTATUS_INDEX = 11;
    private static final int myREGISTRATIONDATE_INDEX = 12;
    private static final int myCUSTOMERMESSAGE_INDEX = 13;
    private static final int myVERIFYCLIENTDETAILS_INDEX = 14;
    private static final int myRECEIVEIDCOPY_INDEX = 15;
    private static final int myACCEPTPARTPAYMENT_INDEX = 16;
    private static final int myACCEPTADDITIONAL_INDEX = 17;
    private static final int myTRANSACTIONSTATUS_INDEX = 18;
    private static final int myTRANSACTIONCONFIRM_INDEX = 19;
    private static final int myMESSAGECODE_INDEX = 20;
    private static final int myMESSAGEDESCRIPTION_INDEX = 21;
    private static final int myCUSTOMFIELD1_INDEX = 22;
    private static final int myCUSTOMFIELD2_INDEX = 23;
    private static final int myCUSTOMFIELD3_INDEX = 24;
    private static final int myTRANSACTIONID_INDEX = 25;
    private static final int myPOLICYPAID_INDEX = 26;
    
    public TClientDetailPolicy_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws java.lang.Exception {
        ns2_myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, java.lang.String.class, ns2_string_TYPE_QNAME);
        ns2_myns2__double__double_Double_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, double.class, ns2_double_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        com.nmt.payapi.TClientDetailPolicy instance = new com.nmt.payapi.TClientDetailPolicy();
        com.nmt.payapi.TClientDetailPolicy_SOAPBuilder builder = null;
        java.lang.Object member;
        boolean isComplete = true;
        javax.xml.namespace.QName elementName;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_PaymentRefNumber_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_PaymentRefNumber_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myPAYMENTREFNUMBER_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setPaymentRefNumber((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_FirstName_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_FirstName_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myFIRSTNAME_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setFirstName((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_LastName_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_LastName_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myLASTNAME_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setLastName((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_IDNumber_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_IDNumber_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myIDNUMBER_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setIDNumber((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_ContactNumber_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_ContactNumber_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myCONTACTNUMBER_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setContactNumber((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_Address_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_Address_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDRESS_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAddress((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AmountDue_QNAME)) {
                member = ns2_myns2__double__double_Double_Serializer.deserialize(ns1_AmountDue_QNAME, reader, context);
                instance.setAmountDue(((Double)member).doubleValue());
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AdditionalAmount_QNAME)) {
                member = ns2_myns2__double__double_Double_Serializer.deserialize(ns1_AdditionalAmount_QNAME, reader, context);
                instance.setAdditionalAmount(((Double)member).doubleValue());
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_DueDate_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_DueDate_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myDUEDATE_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setDueDate((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_Institution_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_Institution_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myINSTITUTION_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setInstitution((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_InstitutionCallCenter_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_InstitutionCallCenter_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myINSTITUTIONCALLCENTER_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setInstitutionCallCenter((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_PolicyStatus_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_PolicyStatus_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myPOLICYSTATUS_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setPolicyStatus((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_RegistrationDate_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_RegistrationDate_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myREGISTRATIONDATE_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setRegistrationDate((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_CustomerMessage_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_CustomerMessage_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myCUSTOMERMESSAGE_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setCustomerMessage((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_VerifyClientDetails_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_VerifyClientDetails_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myVERIFYCLIENTDETAILS_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setVerifyClientDetails((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_ReceiveIDcopy_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_ReceiveIDcopy_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myRECEIVEIDCOPY_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setReceiveIDcopy((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AcceptPartPayment_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AcceptPartPayment_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myACCEPTPARTPAYMENT_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAcceptPartPayment((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_AcceptAdditional_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AcceptAdditional_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myACCEPTADDITIONAL_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAcceptAdditional((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_TransactionStatus_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_TransactionStatus_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myTRANSACTIONSTATUS_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setTransactionStatus((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_TransactionConfirm_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_TransactionConfirm_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myTRANSACTIONCONFIRM_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setTransactionConfirm((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_MessageCode_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_MessageCode_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myMESSAGECODE_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setMessageCode((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_MessageDescription_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_MessageDescription_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myMESSAGEDESCRIPTION_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setMessageDescription((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_CustomField1_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_CustomField1_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myCUSTOMFIELD1_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setCustomField1((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_CustomField2_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_CustomField2_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myCUSTOMFIELD2_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setCustomField2((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_CustomField3_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_CustomField3_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myCUSTOMFIELD3_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setCustomField3((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_TransactionID_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_TransactionID_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myTRANSACTIONID_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setTransactionID((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_PolicyPaid_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_PolicyPaid_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TClientDetailPolicy_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myPOLICYPAID_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setPolicyPaid((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (java.lang.Object)instance : (java.lang.Object)state);
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.nmt.payapi.TClientDetailPolicy instance = (com.nmt.payapi.TClientDetailPolicy)obj;
        
    }
    
    public void doSerializeInstance(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.nmt.payapi.TClientDetailPolicy instance = (com.nmt.payapi.TClientDetailPolicy)obj;
        
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getPaymentRefNumber(), ns1_PaymentRefNumber_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getFirstName(), ns1_FirstName_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getLastName(), ns1_LastName_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getIDNumber(), ns1_IDNumber_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getContactNumber(), ns1_ContactNumber_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAddress(), ns1_Address_QNAME, null, writer, context);
        ns2_myns2__double__double_Double_Serializer.serialize(new Double(instance.getAmountDue()), ns1_AmountDue_QNAME, null, writer, context);
        ns2_myns2__double__double_Double_Serializer.serialize(new Double(instance.getAdditionalAmount()), ns1_AdditionalAmount_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getDueDate(), ns1_DueDate_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getInstitution(), ns1_Institution_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getInstitutionCallCenter(), ns1_InstitutionCallCenter_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getPolicyStatus(), ns1_PolicyStatus_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getRegistrationDate(), ns1_RegistrationDate_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getCustomerMessage(), ns1_CustomerMessage_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getVerifyClientDetails(), ns1_VerifyClientDetails_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getReceiveIDcopy(), ns1_ReceiveIDcopy_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAcceptPartPayment(), ns1_AcceptPartPayment_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAcceptAdditional(), ns1_AcceptAdditional_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getTransactionStatus(), ns1_TransactionStatus_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getTransactionConfirm(), ns1_TransactionConfirm_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getMessageCode(), ns1_MessageCode_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getMessageDescription(), ns1_MessageDescription_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getCustomField1(), ns1_CustomField1_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getCustomField2(), ns1_CustomField2_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getCustomField3(), ns1_CustomField3_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getTransactionID(), ns1_TransactionID_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getPolicyPaid(), ns1_PolicyPaid_QNAME, null, writer, context);
    }
}
