// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class TClientDetailAccount_SOAPBuilder implements SOAPInstanceBuilder {
    private com.nmt.payapi.TClientDetailAccount _instance;
    private java.lang.String paymentRefNumber;
    private java.lang.String firstName;
    private java.lang.String lastName;
    private java.lang.String IDNumber;
    private java.lang.String contactNumber;
    private java.lang.String address;
    private double amountDue;
    private double additionalAmount;
    private java.lang.String dueDate;
    private java.lang.String institution;
    private java.lang.String institutionCallCenter;
    private java.lang.String customerMessage;
    private java.lang.String verifyClientDetails;
    private java.lang.String receiveIDcopy;
    private java.lang.String acceptPartPayment;
    private java.lang.String acceptAdditional;
    private java.lang.String transactionStatus;
    private java.lang.String transactionConfirm;
    private java.lang.String receiptMessage;
    private java.lang.String transactionID;
    private java.lang.String messageCode;
    private java.lang.String messageDescription;
    private com.nmt.payapi.TClientDetailAccArray[] detailArr;
    private static final int myPAYMENTREFNUMBER_INDEX = 0;
    private static final int myFIRSTNAME_INDEX = 1;
    private static final int myLASTNAME_INDEX = 2;
    private static final int myIDNUMBER_INDEX = 3;
    private static final int myCONTACTNUMBER_INDEX = 4;
    private static final int myADDRESS_INDEX = 5;
    private static final int myAMOUNTDUE_INDEX = 6;
    private static final int myADDITIONALAMOUNT_INDEX = 7;
    private static final int myDUEDATE_INDEX = 8;
    private static final int myINSTITUTION_INDEX = 9;
    private static final int myINSTITUTIONCALLCENTER_INDEX = 10;
    private static final int myCUSTOMERMESSAGE_INDEX = 11;
    private static final int myVERIFYCLIENTDETAILS_INDEX = 12;
    private static final int myRECEIVEIDCOPY_INDEX = 13;
    private static final int myACCEPTPARTPAYMENT_INDEX = 14;
    private static final int myACCEPTADDITIONAL_INDEX = 15;
    private static final int myTRANSACTIONSTATUS_INDEX = 16;
    private static final int myTRANSACTIONCONFIRM_INDEX = 17;
    private static final int myRECEIPTMESSAGE_INDEX = 18;
    private static final int myTRANSACTIONID_INDEX = 19;
    private static final int myMESSAGECODE_INDEX = 20;
    private static final int myMESSAGEDESCRIPTION_INDEX = 21;
    private static final int myDETAILARR_INDEX = 22;
    
    public TClientDetailAccount_SOAPBuilder() {
    }
    
    public void setPaymentRefNumber(java.lang.String paymentRefNumber) {
        this.paymentRefNumber = paymentRefNumber;
    }
    
    public void setFirstName(java.lang.String firstName) {
        this.firstName = firstName;
    }
    
    public void setLastName(java.lang.String lastName) {
        this.lastName = lastName;
    }
    
    public void setIDNumber(java.lang.String IDNumber) {
        this.IDNumber = IDNumber;
    }
    
    public void setContactNumber(java.lang.String contactNumber) {
        this.contactNumber = contactNumber;
    }
    
    public void setAddress(java.lang.String address) {
        this.address = address;
    }
    
    public void setAmountDue(double amountDue) {
        this.amountDue = amountDue;
    }
    
    public void setAdditionalAmount(double additionalAmount) {
        this.additionalAmount = additionalAmount;
    }
    
    public void setDueDate(java.lang.String dueDate) {
        this.dueDate = dueDate;
    }
    
    public void setInstitution(java.lang.String institution) {
        this.institution = institution;
    }
    
    public void setInstitutionCallCenter(java.lang.String institutionCallCenter) {
        this.institutionCallCenter = institutionCallCenter;
    }
    
    public void setCustomerMessage(java.lang.String customerMessage) {
        this.customerMessage = customerMessage;
    }
    
    public void setVerifyClientDetails(java.lang.String verifyClientDetails) {
        this.verifyClientDetails = verifyClientDetails;
    }
    
    public void setReceiveIDcopy(java.lang.String receiveIDcopy) {
        this.receiveIDcopy = receiveIDcopy;
    }
    
    public void setAcceptPartPayment(java.lang.String acceptPartPayment) {
        this.acceptPartPayment = acceptPartPayment;
    }
    
    public void setAcceptAdditional(java.lang.String acceptAdditional) {
        this.acceptAdditional = acceptAdditional;
    }
    
    public void setTransactionStatus(java.lang.String transactionStatus) {
        this.transactionStatus = transactionStatus;
    }
    
    public void setTransactionConfirm(java.lang.String transactionConfirm) {
        this.transactionConfirm = transactionConfirm;
    }
    
    public void setReceiptMessage(java.lang.String receiptMessage) {
        this.receiptMessage = receiptMessage;
    }
    
    public void setTransactionID(java.lang.String transactionID) {
        this.transactionID = transactionID;
    }
    
    public void setMessageCode(java.lang.String messageCode) {
        this.messageCode = messageCode;
    }
    
    public void setMessageDescription(java.lang.String messageDescription) {
        this.messageDescription = messageDescription;
    }
    
    public void setDetailArr(com.nmt.payapi.TClientDetailAccArray[] detailArr) {
        this.detailArr = detailArr;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myPAYMENTREFNUMBER_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myFIRSTNAME_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myLASTNAME_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myIDNUMBER_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myCONTACTNUMBER_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDRESS_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myDUEDATE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myINSTITUTION_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myINSTITUTIONCALLCENTER_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myCUSTOMERMESSAGE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myVERIFYCLIENTDETAILS_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myRECEIVEIDCOPY_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myACCEPTPARTPAYMENT_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myACCEPTADDITIONAL_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myTRANSACTIONSTATUS_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myTRANSACTIONCONFIRM_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myRECEIPTMESSAGE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myTRANSACTIONID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myMESSAGECODE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myMESSAGEDESCRIPTION_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myDETAILARR_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myPAYMENTREFNUMBER_INDEX:
                    _instance.setPaymentRefNumber((java.lang.String)memberValue);
                    break;
                case myFIRSTNAME_INDEX:
                    _instance.setFirstName((java.lang.String)memberValue);
                    break;
                case myLASTNAME_INDEX:
                    _instance.setLastName((java.lang.String)memberValue);
                    break;
                case myIDNUMBER_INDEX:
                    _instance.setIDNumber((java.lang.String)memberValue);
                    break;
                case myCONTACTNUMBER_INDEX:
                    _instance.setContactNumber((java.lang.String)memberValue);
                    break;
                case myADDRESS_INDEX:
                    _instance.setAddress((java.lang.String)memberValue);
                    break;
                case myDUEDATE_INDEX:
                    _instance.setDueDate((java.lang.String)memberValue);
                    break;
                case myINSTITUTION_INDEX:
                    _instance.setInstitution((java.lang.String)memberValue);
                    break;
                case myINSTITUTIONCALLCENTER_INDEX:
                    _instance.setInstitutionCallCenter((java.lang.String)memberValue);
                    break;
                case myCUSTOMERMESSAGE_INDEX:
                    _instance.setCustomerMessage((java.lang.String)memberValue);
                    break;
                case myVERIFYCLIENTDETAILS_INDEX:
                    _instance.setVerifyClientDetails((java.lang.String)memberValue);
                    break;
                case myRECEIVEIDCOPY_INDEX:
                    _instance.setReceiveIDcopy((java.lang.String)memberValue);
                    break;
                case myACCEPTPARTPAYMENT_INDEX:
                    _instance.setAcceptPartPayment((java.lang.String)memberValue);
                    break;
                case myACCEPTADDITIONAL_INDEX:
                    _instance.setAcceptAdditional((java.lang.String)memberValue);
                    break;
                case myTRANSACTIONSTATUS_INDEX:
                    _instance.setTransactionStatus((java.lang.String)memberValue);
                    break;
                case myTRANSACTIONCONFIRM_INDEX:
                    _instance.setTransactionConfirm((java.lang.String)memberValue);
                    break;
                case myRECEIPTMESSAGE_INDEX:
                    _instance.setReceiptMessage((java.lang.String)memberValue);
                    break;
                case myTRANSACTIONID_INDEX:
                    _instance.setTransactionID((java.lang.String)memberValue);
                    break;
                case myMESSAGECODE_INDEX:
                    _instance.setMessageCode((java.lang.String)memberValue);
                    break;
                case myMESSAGEDESCRIPTION_INDEX:
                    _instance.setMessageDescription((java.lang.String)memberValue);
                    break;
                case myDETAILARR_INDEX:
                    _instance.setDetailArr((com.nmt.payapi.TClientDetailAccArray[])memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.nmt.payapi.TClientDetailAccount)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
