// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;


public class TClientDetailAccArray {
    protected java.lang.String additionalField1;
    protected java.lang.String additionalField2;
    protected java.lang.String additionalField3;
    protected java.lang.String additionalField4;
    protected java.lang.String additionalField5;
    protected java.lang.String additionalField6;
    protected java.lang.String additionalField7;
    protected java.lang.String additionalField8;
    protected java.lang.String additionalField9;
    protected java.lang.String additionalField10;
    protected java.lang.String additionalField11;
    protected java.lang.String additionalField12;
    protected java.lang.String additionalField13;
    protected java.lang.String additionalField14;
    protected java.lang.String additionalField15;
    protected java.lang.String additionalField16;
    protected java.lang.String additionalField17;
    protected java.lang.String additionalField18;
    protected java.lang.String additionalField19;
    protected java.lang.String additionalField20;
    protected com.nmt.payapi.TClientDetailAccSubArray[] subDetail;
    
    public TClientDetailAccArray() {
    }
    
    public TClientDetailAccArray(java.lang.String additionalField1, java.lang.String additionalField2, java.lang.String additionalField3, java.lang.String additionalField4, java.lang.String additionalField5, java.lang.String additionalField6, java.lang.String additionalField7, java.lang.String additionalField8, java.lang.String additionalField9, java.lang.String additionalField10, java.lang.String additionalField11, java.lang.String additionalField12, java.lang.String additionalField13, java.lang.String additionalField14, java.lang.String additionalField15, java.lang.String additionalField16, java.lang.String additionalField17, java.lang.String additionalField18, java.lang.String additionalField19, java.lang.String additionalField20, com.nmt.payapi.TClientDetailAccSubArray[] subDetail) {
        this.additionalField1 = additionalField1;
        this.additionalField2 = additionalField2;
        this.additionalField3 = additionalField3;
        this.additionalField4 = additionalField4;
        this.additionalField5 = additionalField5;
        this.additionalField6 = additionalField6;
        this.additionalField7 = additionalField7;
        this.additionalField8 = additionalField8;
        this.additionalField9 = additionalField9;
        this.additionalField10 = additionalField10;
        this.additionalField11 = additionalField11;
        this.additionalField12 = additionalField12;
        this.additionalField13 = additionalField13;
        this.additionalField14 = additionalField14;
        this.additionalField15 = additionalField15;
        this.additionalField16 = additionalField16;
        this.additionalField17 = additionalField17;
        this.additionalField18 = additionalField18;
        this.additionalField19 = additionalField19;
        this.additionalField20 = additionalField20;
        this.subDetail = subDetail;
    }
    
    public java.lang.String getAdditionalField1() {
        return additionalField1;
    }
    
    public void setAdditionalField1(java.lang.String additionalField1) {
        this.additionalField1 = additionalField1;
    }
    
    public java.lang.String getAdditionalField2() {
        return additionalField2;
    }
    
    public void setAdditionalField2(java.lang.String additionalField2) {
        this.additionalField2 = additionalField2;
    }
    
    public java.lang.String getAdditionalField3() {
        return additionalField3;
    }
    
    public void setAdditionalField3(java.lang.String additionalField3) {
        this.additionalField3 = additionalField3;
    }
    
    public java.lang.String getAdditionalField4() {
        return additionalField4;
    }
    
    public void setAdditionalField4(java.lang.String additionalField4) {
        this.additionalField4 = additionalField4;
    }
    
    public java.lang.String getAdditionalField5() {
        return additionalField5;
    }
    
    public void setAdditionalField5(java.lang.String additionalField5) {
        this.additionalField5 = additionalField5;
    }
    
    public java.lang.String getAdditionalField6() {
        return additionalField6;
    }
    
    public void setAdditionalField6(java.lang.String additionalField6) {
        this.additionalField6 = additionalField6;
    }
    
    public java.lang.String getAdditionalField7() {
        return additionalField7;
    }
    
    public void setAdditionalField7(java.lang.String additionalField7) {
        this.additionalField7 = additionalField7;
    }
    
    public java.lang.String getAdditionalField8() {
        return additionalField8;
    }
    
    public void setAdditionalField8(java.lang.String additionalField8) {
        this.additionalField8 = additionalField8;
    }
    
    public java.lang.String getAdditionalField9() {
        return additionalField9;
    }
    
    public void setAdditionalField9(java.lang.String additionalField9) {
        this.additionalField9 = additionalField9;
    }
    
    public java.lang.String getAdditionalField10() {
        return additionalField10;
    }
    
    public void setAdditionalField10(java.lang.String additionalField10) {
        this.additionalField10 = additionalField10;
    }
    
    public java.lang.String getAdditionalField11() {
        return additionalField11;
    }
    
    public void setAdditionalField11(java.lang.String additionalField11) {
        this.additionalField11 = additionalField11;
    }
    
    public java.lang.String getAdditionalField12() {
        return additionalField12;
    }
    
    public void setAdditionalField12(java.lang.String additionalField12) {
        this.additionalField12 = additionalField12;
    }
    
    public java.lang.String getAdditionalField13() {
        return additionalField13;
    }
    
    public void setAdditionalField13(java.lang.String additionalField13) {
        this.additionalField13 = additionalField13;
    }
    
    public java.lang.String getAdditionalField14() {
        return additionalField14;
    }
    
    public void setAdditionalField14(java.lang.String additionalField14) {
        this.additionalField14 = additionalField14;
    }
    
    public java.lang.String getAdditionalField15() {
        return additionalField15;
    }
    
    public void setAdditionalField15(java.lang.String additionalField15) {
        this.additionalField15 = additionalField15;
    }
    
    public java.lang.String getAdditionalField16() {
        return additionalField16;
    }
    
    public void setAdditionalField16(java.lang.String additionalField16) {
        this.additionalField16 = additionalField16;
    }
    
    public java.lang.String getAdditionalField17() {
        return additionalField17;
    }
    
    public void setAdditionalField17(java.lang.String additionalField17) {
        this.additionalField17 = additionalField17;
    }
    
    public java.lang.String getAdditionalField18() {
        return additionalField18;
    }
    
    public void setAdditionalField18(java.lang.String additionalField18) {
        this.additionalField18 = additionalField18;
    }
    
    public java.lang.String getAdditionalField19() {
        return additionalField19;
    }
    
    public void setAdditionalField19(java.lang.String additionalField19) {
        this.additionalField19 = additionalField19;
    }
    
    public java.lang.String getAdditionalField20() {
        return additionalField20;
    }
    
    public void setAdditionalField20(java.lang.String additionalField20) {
        this.additionalField20 = additionalField20;
    }
    
    public com.nmt.payapi.TClientDetailAccSubArray[] getSubDetail() {
        return subDetail;
    }
    
    public void setSubDetail(com.nmt.payapi.TClientDetailAccSubArray[] subDetail) {
        this.subDetail = subDetail;
    }
}
