// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;


public class TConfirmP {
    protected java.lang.String messageCode;
    protected java.lang.String messageDescription;
    protected java.lang.String additionalField1;
    protected java.lang.String additionalField2;
    
    public TConfirmP() {
    }
    
    public TConfirmP(java.lang.String messageCode, java.lang.String messageDescription, java.lang.String additionalField1, java.lang.String additionalField2) {
        this.messageCode = messageCode;
        this.messageDescription = messageDescription;
        this.additionalField1 = additionalField1;
        this.additionalField2 = additionalField2;
    }
    
    public java.lang.String getMessageCode() {
        return messageCode;
    }
    
    public void setMessageCode(java.lang.String messageCode) {
        this.messageCode = messageCode;
    }
    
    public java.lang.String getMessageDescription() {
        return messageDescription;
    }
    
    public void setMessageDescription(java.lang.String messageDescription) {
        this.messageDescription = messageDescription;
    }
    
    public java.lang.String getAdditionalField1() {
        return additionalField1;
    }
    
    public void setAdditionalField1(java.lang.String additionalField1) {
        this.additionalField1 = additionalField1;
    }
    
    public java.lang.String getAdditionalField2() {
        return additionalField2;
    }
    
    public void setAdditionalField2(java.lang.String additionalField2) {
        this.additionalField2 = additionalField2;
    }
}
