// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;


public class TEchoResult {
    protected java.lang.String messageCode;
    protected java.lang.String messageDescription;
    protected java.lang.String echoMessage;
    
    public TEchoResult() {
    }
    
    public TEchoResult(java.lang.String messageCode, java.lang.String messageDescription, java.lang.String echoMessage) {
        this.messageCode = messageCode;
        this.messageDescription = messageDescription;
        this.echoMessage = echoMessage;
    }
    
    public java.lang.String getMessageCode() {
        return messageCode;
    }
    
    public void setMessageCode(java.lang.String messageCode) {
        this.messageCode = messageCode;
    }
    
    public java.lang.String getMessageDescription() {
        return messageDescription;
    }
    
    public void setMessageDescription(java.lang.String messageDescription) {
        this.messageDescription = messageDescription;
    }
    
    public java.lang.String getEchoMessage() {
        return echoMessage;
    }
    
    public void setEchoMessage(java.lang.String echoMessage) {
        this.echoMessage = echoMessage;
    }
}
