// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class TPayoutDetails_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_PaymentRefNumber_QNAME = new QName("", "PaymentRefNumber");
    private static final javax.xml.namespace.QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer ns2_myns2_string__java_lang_String_String_Serializer;
    private static final javax.xml.namespace.QName ns1_FirstName_QNAME = new QName("", "FirstName");
    private static final javax.xml.namespace.QName ns1_LastName_QNAME = new QName("", "LastName");
    private static final javax.xml.namespace.QName ns1_IDNumber_QNAME = new QName("", "IDNumber");
    private static final javax.xml.namespace.QName ns1_ContactNumber_QNAME = new QName("", "ContactNumber");
    private static final javax.xml.namespace.QName ns1_Address_QNAME = new QName("", "Address");
    private static final javax.xml.namespace.QName ns1_PayAmount_QNAME = new QName("", "PayAmount");
    private static final javax.xml.namespace.QName ns2_double_TYPE_QNAME = SchemaConstants.QNAME_TYPE_DOUBLE;
    private CombinedSerializer ns2_myns2__double__double_Double_Serializer;
    private static final javax.xml.namespace.QName ns1_Pincode_QNAME = new QName("", "Pincode");
    private static final javax.xml.namespace.QName ns1_Institution_QNAME = new QName("", "Institution");
    private static final javax.xml.namespace.QName ns1_InstitutionCallCenter_QNAME = new QName("", "InstitutionCallCenter");
    private static final javax.xml.namespace.QName ns1_CustomerMessage_QNAME = new QName("", "CustomerMessage");
    private static final javax.xml.namespace.QName ns1_VerifyClientDetails_QNAME = new QName("", "VerifyClientDetails");
    private static final javax.xml.namespace.QName ns1_ReceiveIDcopy_QNAME = new QName("", "ReceiveIDcopy");
    private static final javax.xml.namespace.QName ns1_TransactionStatus_QNAME = new QName("", "TransactionStatus");
    private static final javax.xml.namespace.QName ns1_ReceiptMessage_QNAME = new QName("", "ReceiptMessage");
    private static final javax.xml.namespace.QName ns1_TransactionID_QNAME = new QName("", "TransactionID");
    private static final javax.xml.namespace.QName ns1_ClientMessage_QNAME = new QName("", "ClientMessage");
    private static final int myPAYMENTREFNUMBER_INDEX = 0;
    private static final int myFIRSTNAME_INDEX = 1;
    private static final int myLASTNAME_INDEX = 2;
    private static final int myIDNUMBER_INDEX = 3;
    private static final int myCONTACTNUMBER_INDEX = 4;
    private static final int myADDRESS_INDEX = 5;
    private static final int myPAYAMOUNT_INDEX = 6;
    private static final int myPINCODE_INDEX = 7;
    private static final int myINSTITUTION_INDEX = 8;
    private static final int myINSTITUTIONCALLCENTER_INDEX = 9;
    private static final int myCUSTOMERMESSAGE_INDEX = 10;
    private static final int myVERIFYCLIENTDETAILS_INDEX = 11;
    private static final int myRECEIVEIDCOPY_INDEX = 12;
    private static final int myTRANSACTIONSTATUS_INDEX = 13;
    private static final int myRECEIPTMESSAGE_INDEX = 14;
    private static final int myTRANSACTIONID_INDEX = 15;
    private static final int myCLIENTMESSAGE_INDEX = 16;
    
    public TPayoutDetails_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws java.lang.Exception {
        ns2_myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, java.lang.String.class, ns2_string_TYPE_QNAME);
        ns2_myns2__double__double_Double_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, double.class, ns2_double_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        com.nmt.payapi.TPayoutDetails instance = new com.nmt.payapi.TPayoutDetails();
        com.nmt.payapi.TPayoutDetails_SOAPBuilder builder = null;
        java.lang.Object member;
        boolean isComplete = true;
        javax.xml.namespace.QName elementName;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_PaymentRefNumber_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_PaymentRefNumber_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TPayoutDetails_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myPAYMENTREFNUMBER_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setPaymentRefNumber((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_FirstName_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_FirstName_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TPayoutDetails_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myFIRSTNAME_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setFirstName((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_LastName_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_LastName_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TPayoutDetails_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myLASTNAME_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setLastName((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_IDNumber_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_IDNumber_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TPayoutDetails_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myIDNUMBER_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setIDNumber((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_ContactNumber_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_ContactNumber_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TPayoutDetails_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myCONTACTNUMBER_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setContactNumber((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_Address_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_Address_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TPayoutDetails_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDRESS_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAddress((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_PayAmount_QNAME)) {
                member = ns2_myns2__double__double_Double_Serializer.deserialize(ns1_PayAmount_QNAME, reader, context);
                instance.setPayAmount(((Double)member).doubleValue());
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_Pincode_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_Pincode_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TPayoutDetails_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myPINCODE_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setPincode((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_Institution_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_Institution_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TPayoutDetails_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myINSTITUTION_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setInstitution((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_InstitutionCallCenter_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_InstitutionCallCenter_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TPayoutDetails_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myINSTITUTIONCALLCENTER_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setInstitutionCallCenter((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_CustomerMessage_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_CustomerMessage_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TPayoutDetails_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myCUSTOMERMESSAGE_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setCustomerMessage((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_VerifyClientDetails_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_VerifyClientDetails_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TPayoutDetails_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myVERIFYCLIENTDETAILS_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setVerifyClientDetails((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_ReceiveIDcopy_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_ReceiveIDcopy_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TPayoutDetails_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myRECEIVEIDCOPY_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setReceiveIDcopy((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_TransactionStatus_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_TransactionStatus_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TPayoutDetails_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myTRANSACTIONSTATUS_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setTransactionStatus((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_ReceiptMessage_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_ReceiptMessage_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TPayoutDetails_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myRECEIPTMESSAGE_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setReceiptMessage((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_TransactionID_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_TransactionID_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TPayoutDetails_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myTRANSACTIONID_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setTransactionID((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_ClientMessage_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_ClientMessage_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.TPayoutDetails_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myCLIENTMESSAGE_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setClientMessage((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (java.lang.Object)instance : (java.lang.Object)state);
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.nmt.payapi.TPayoutDetails instance = (com.nmt.payapi.TPayoutDetails)obj;
        
    }
    
    public void doSerializeInstance(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.nmt.payapi.TPayoutDetails instance = (com.nmt.payapi.TPayoutDetails)obj;
        
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getPaymentRefNumber(), ns1_PaymentRefNumber_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getFirstName(), ns1_FirstName_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getLastName(), ns1_LastName_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getIDNumber(), ns1_IDNumber_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getContactNumber(), ns1_ContactNumber_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAddress(), ns1_Address_QNAME, null, writer, context);
        ns2_myns2__double__double_Double_Serializer.serialize(new Double(instance.getPayAmount()), ns1_PayAmount_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getPincode(), ns1_Pincode_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getInstitution(), ns1_Institution_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getInstitutionCallCenter(), ns1_InstitutionCallCenter_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getCustomerMessage(), ns1_CustomerMessage_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getVerifyClientDetails(), ns1_VerifyClientDetails_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getReceiveIDcopy(), ns1_ReceiveIDcopy_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getTransactionStatus(), ns1_TransactionStatus_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getReceiptMessage(), ns1_ReceiptMessage_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getTransactionID(), ns1_TransactionID_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getClientMessage(), ns1_ClientMessage_QNAME, null, writer, context);
    }
}
