// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;


public class TPayoutDetails {
    protected java.lang.String paymentRefNumber;
    protected java.lang.String firstName;
    protected java.lang.String lastName;
    protected java.lang.String IDNumber;
    protected java.lang.String contactNumber;
    protected java.lang.String address;
    protected double payAmount;
    protected java.lang.String pincode;
    protected java.lang.String institution;
    protected java.lang.String institutionCallCenter;
    protected java.lang.String customerMessage;
    protected java.lang.String verifyClientDetails;
    protected java.lang.String receiveIDcopy;
    protected java.lang.String transactionStatus;
    protected java.lang.String receiptMessage;
    protected java.lang.String transactionID;
    protected java.lang.String clientMessage;
    
    public TPayoutDetails() {
    }
    
    public TPayoutDetails(java.lang.String paymentRefNumber, java.lang.String firstName, java.lang.String lastName, java.lang.String IDNumber, java.lang.String contactNumber, java.lang.String address, double payAmount, java.lang.String pincode, java.lang.String institution, java.lang.String institutionCallCenter, java.lang.String customerMessage, java.lang.String verifyClientDetails, java.lang.String receiveIDcopy, java.lang.String transactionStatus, java.lang.String receiptMessage, java.lang.String transactionID, java.lang.String clientMessage) {
        this.paymentRefNumber = paymentRefNumber;
        this.firstName = firstName;
        this.lastName = lastName;
        this.IDNumber = IDNumber;
        this.contactNumber = contactNumber;
        this.address = address;
        this.payAmount = payAmount;
        this.pincode = pincode;
        this.institution = institution;
        this.institutionCallCenter = institutionCallCenter;
        this.customerMessage = customerMessage;
        this.verifyClientDetails = verifyClientDetails;
        this.receiveIDcopy = receiveIDcopy;
        this.transactionStatus = transactionStatus;
        this.receiptMessage = receiptMessage;
        this.transactionID = transactionID;
        this.clientMessage = clientMessage;
    }
    
    public java.lang.String getPaymentRefNumber() {
        return paymentRefNumber;
    }
    
    public void setPaymentRefNumber(java.lang.String paymentRefNumber) {
        this.paymentRefNumber = paymentRefNumber;
    }
    
    public java.lang.String getFirstName() {
        return firstName;
    }
    
    public void setFirstName(java.lang.String firstName) {
        this.firstName = firstName;
    }
    
    public java.lang.String getLastName() {
        return lastName;
    }
    
    public void setLastName(java.lang.String lastName) {
        this.lastName = lastName;
    }
    
    public java.lang.String getIDNumber() {
        return IDNumber;
    }
    
    public void setIDNumber(java.lang.String IDNumber) {
        this.IDNumber = IDNumber;
    }
    
    public java.lang.String getContactNumber() {
        return contactNumber;
    }
    
    public void setContactNumber(java.lang.String contactNumber) {
        this.contactNumber = contactNumber;
    }
    
    public java.lang.String getAddress() {
        return address;
    }
    
    public void setAddress(java.lang.String address) {
        this.address = address;
    }
    
    public double getPayAmount() {
        return payAmount;
    }
    
    public void setPayAmount(double payAmount) {
        this.payAmount = payAmount;
    }
    
    public java.lang.String getPincode() {
        return pincode;
    }
    
    public void setPincode(java.lang.String pincode) {
        this.pincode = pincode;
    }
    
    public java.lang.String getInstitution() {
        return institution;
    }
    
    public void setInstitution(java.lang.String institution) {
        this.institution = institution;
    }
    
    public java.lang.String getInstitutionCallCenter() {
        return institutionCallCenter;
    }
    
    public void setInstitutionCallCenter(java.lang.String institutionCallCenter) {
        this.institutionCallCenter = institutionCallCenter;
    }
    
    public java.lang.String getCustomerMessage() {
        return customerMessage;
    }
    
    public void setCustomerMessage(java.lang.String customerMessage) {
        this.customerMessage = customerMessage;
    }
    
    public java.lang.String getVerifyClientDetails() {
        return verifyClientDetails;
    }
    
    public void setVerifyClientDetails(java.lang.String verifyClientDetails) {
        this.verifyClientDetails = verifyClientDetails;
    }
    
    public java.lang.String getReceiveIDcopy() {
        return receiveIDcopy;
    }
    
    public void setReceiveIDcopy(java.lang.String receiveIDcopy) {
        this.receiveIDcopy = receiveIDcopy;
    }
    
    public java.lang.String getTransactionStatus() {
        return transactionStatus;
    }
    
    public void setTransactionStatus(java.lang.String transactionStatus) {
        this.transactionStatus = transactionStatus;
    }
    
    public java.lang.String getReceiptMessage() {
        return receiptMessage;
    }
    
    public void setReceiptMessage(java.lang.String receiptMessage) {
        this.receiptMessage = receiptMessage;
    }
    
    public java.lang.String getTransactionID() {
        return transactionID;
    }
    
    public void setTransactionID(java.lang.String transactionID) {
        this.transactionID = transactionID;
    }
    
    public java.lang.String getClientMessage() {
        return clientMessage;
    }
    
    public void setClientMessage(java.lang.String clientMessage) {
        this.clientMessage = clientMessage;
    }
}
