// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class TReconResults_SOAPBuilder implements SOAPInstanceBuilder {
    private com.nmt.payapi.TReconResults _instance;
    private java.lang.String transactionID;
    private java.lang.String transactionDate;
    private double amount;
    private java.lang.String refNo;
    private java.lang.String storeID;
    private java.lang.String tillID;
    private java.lang.String policyNo;
    private java.lang.String messageCode;
    private java.lang.String messageDescription;
    private java.lang.String transStatus;
    private static final int myTRANSACTIONID_INDEX = 0;
    private static final int myTRANSACTIONDATE_INDEX = 1;
    private static final int myAMOUNT_INDEX = 2;
    private static final int myREFNO_INDEX = 3;
    private static final int mySTOREID_INDEX = 4;
    private static final int myTILLID_INDEX = 5;
    private static final int myPOLICYNO_INDEX = 6;
    private static final int myMESSAGECODE_INDEX = 7;
    private static final int myMESSAGEDESCRIPTION_INDEX = 8;
    private static final int myTRANSSTATUS_INDEX = 9;
    
    public TReconResults_SOAPBuilder() {
    }
    
    public void setTransactionID(java.lang.String transactionID) {
        this.transactionID = transactionID;
    }
    
    public void setTransactionDate(java.lang.String transactionDate) {
        this.transactionDate = transactionDate;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    
    public void setRefNo(java.lang.String refNo) {
        this.refNo = refNo;
    }
    
    public void setStoreID(java.lang.String storeID) {
        this.storeID = storeID;
    }
    
    public void setTillID(java.lang.String tillID) {
        this.tillID = tillID;
    }
    
    public void setPolicyNo(java.lang.String policyNo) {
        this.policyNo = policyNo;
    }
    
    public void setMessageCode(java.lang.String messageCode) {
        this.messageCode = messageCode;
    }
    
    public void setMessageDescription(java.lang.String messageDescription) {
        this.messageDescription = messageDescription;
    }
    
    public void setTransStatus(java.lang.String transStatus) {
        this.transStatus = transStatus;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myTRANSACTIONID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myTRANSACTIONDATE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myREFNO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySTOREID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myTILLID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myPOLICYNO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myMESSAGECODE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myMESSAGEDESCRIPTION_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myTRANSSTATUS_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myTRANSACTIONID_INDEX:
                    _instance.setTransactionID((java.lang.String)memberValue);
                    break;
                case myTRANSACTIONDATE_INDEX:
                    _instance.setTransactionDate((java.lang.String)memberValue);
                    break;
                case myREFNO_INDEX:
                    _instance.setRefNo((java.lang.String)memberValue);
                    break;
                case mySTOREID_INDEX:
                    _instance.setStoreID((java.lang.String)memberValue);
                    break;
                case myTILLID_INDEX:
                    _instance.setTillID((java.lang.String)memberValue);
                    break;
                case myPOLICYNO_INDEX:
                    _instance.setPolicyNo((java.lang.String)memberValue);
                    break;
                case myMESSAGECODE_INDEX:
                    _instance.setMessageCode((java.lang.String)memberValue);
                    break;
                case myMESSAGEDESCRIPTION_INDEX:
                    _instance.setMessageDescription((java.lang.String)memberValue);
                    break;
                case myTRANSSTATUS_INDEX:
                    _instance.setTransStatus((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.nmt.payapi.TReconResults)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
