// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;


public class TReconResults {
    protected java.lang.String transactionID;
    protected java.lang.String transactionDate;
    protected double amount;
    protected java.lang.String refNo;
    protected java.lang.String storeID;
    protected java.lang.String tillID;
    protected java.lang.String policyNo;
    protected java.lang.String messageCode;
    protected java.lang.String messageDescription;
    protected java.lang.String transStatus;
    
    public TReconResults() {
    }
    
    public TReconResults(java.lang.String transactionID, java.lang.String transactionDate, double amount, java.lang.String refNo, java.lang.String storeID, java.lang.String tillID, java.lang.String policyNo, java.lang.String messageCode, java.lang.String messageDescription, java.lang.String transStatus) {
        this.transactionID = transactionID;
        this.transactionDate = transactionDate;
        this.amount = amount;
        this.refNo = refNo;
        this.storeID = storeID;
        this.tillID = tillID;
        this.policyNo = policyNo;
        this.messageCode = messageCode;
        this.messageDescription = messageDescription;
        this.transStatus = transStatus;
    }
    
    public java.lang.String getTransactionID() {
        return transactionID;
    }
    
    public void setTransactionID(java.lang.String transactionID) {
        this.transactionID = transactionID;
    }
    
    public java.lang.String getTransactionDate() {
        return transactionDate;
    }
    
    public void setTransactionDate(java.lang.String transactionDate) {
        this.transactionDate = transactionDate;
    }
    
    public double getAmount() {
        return amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    
    public java.lang.String getRefNo() {
        return refNo;
    }
    
    public void setRefNo(java.lang.String refNo) {
        this.refNo = refNo;
    }
    
    public java.lang.String getStoreID() {
        return storeID;
    }
    
    public void setStoreID(java.lang.String storeID) {
        this.storeID = storeID;
    }
    
    public java.lang.String getTillID() {
        return tillID;
    }
    
    public void setTillID(java.lang.String tillID) {
        this.tillID = tillID;
    }
    
    public java.lang.String getPolicyNo() {
        return policyNo;
    }
    
    public void setPolicyNo(java.lang.String policyNo) {
        this.policyNo = policyNo;
    }
    
    public java.lang.String getMessageCode() {
        return messageCode;
    }
    
    public void setMessageCode(java.lang.String messageCode) {
        this.messageCode = messageCode;
    }
    
    public java.lang.String getMessageDescription() {
        return messageDescription;
    }
    
    public void setMessageDescription(java.lang.String messageDescription) {
        this.messageDescription = messageDescription;
    }
    
    public java.lang.String getTransStatus() {
        return transStatus;
    }
    
    public void setTransStatus(java.lang.String transStatus) {
        this.transStatus = transStatus;
    }
}
