// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class TRegisterPolicy_SOAPBuilder implements SOAPInstanceBuilder {
    private com.nmt.payapi.TRegisterPolicy _instance;
    private java.lang.String messageCode;
    private java.lang.String messageDescription;
    private java.lang.String policyNumber;
    private java.lang.String institution;
    private java.lang.String institutionCallCenter;
    private double amountDue;
    private boolean payAfterRegister;
    private java.lang.String receiptReferenceNumber;
    private com.nmt.payapi.TClientDetailPolicy clientInfo;
    private static final int myMESSAGECODE_INDEX = 0;
    private static final int myMESSAGEDESCRIPTION_INDEX = 1;
    private static final int myPOLICYNUMBER_INDEX = 2;
    private static final int myINSTITUTION_INDEX = 3;
    private static final int myINSTITUTIONCALLCENTER_INDEX = 4;
    private static final int myAMOUNTDUE_INDEX = 5;
    private static final int myPAYAFTERREGISTER_INDEX = 6;
    private static final int myRECEIPTREFERENCENUMBER_INDEX = 7;
    private static final int myCLIENTINFO_INDEX = 8;
    
    public TRegisterPolicy_SOAPBuilder() {
    }
    
    public void setMessageCode(java.lang.String messageCode) {
        this.messageCode = messageCode;
    }
    
    public void setMessageDescription(java.lang.String messageDescription) {
        this.messageDescription = messageDescription;
    }
    
    public void setPolicyNumber(java.lang.String policyNumber) {
        this.policyNumber = policyNumber;
    }
    
    public void setInstitution(java.lang.String institution) {
        this.institution = institution;
    }
    
    public void setInstitutionCallCenter(java.lang.String institutionCallCenter) {
        this.institutionCallCenter = institutionCallCenter;
    }
    
    public void setAmountDue(double amountDue) {
        this.amountDue = amountDue;
    }
    
    public void setPayAfterRegister(boolean payAfterRegister) {
        this.payAfterRegister = payAfterRegister;
    }
    
    public void setReceiptReferenceNumber(java.lang.String receiptReferenceNumber) {
        this.receiptReferenceNumber = receiptReferenceNumber;
    }
    
    public void setClientInfo(com.nmt.payapi.TClientDetailPolicy clientInfo) {
        this.clientInfo = clientInfo;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myMESSAGECODE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myMESSAGEDESCRIPTION_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myPOLICYNUMBER_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myINSTITUTION_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myINSTITUTIONCALLCENTER_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myRECEIPTREFERENCENUMBER_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myCLIENTINFO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myMESSAGECODE_INDEX:
                    _instance.setMessageCode((java.lang.String)memberValue);
                    break;
                case myMESSAGEDESCRIPTION_INDEX:
                    _instance.setMessageDescription((java.lang.String)memberValue);
                    break;
                case myPOLICYNUMBER_INDEX:
                    _instance.setPolicyNumber((java.lang.String)memberValue);
                    break;
                case myINSTITUTION_INDEX:
                    _instance.setInstitution((java.lang.String)memberValue);
                    break;
                case myINSTITUTIONCALLCENTER_INDEX:
                    _instance.setInstitutionCallCenter((java.lang.String)memberValue);
                    break;
                case myRECEIPTREFERENCENUMBER_INDEX:
                    _instance.setReceiptReferenceNumber((java.lang.String)memberValue);
                    break;
                case myCLIENTINFO_INDEX:
                    _instance.setClientInfo((com.nmt.payapi.TClientDetailPolicy)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.nmt.payapi.TRegisterPolicy)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
