// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;


public class TRegisterPolicy {
    protected java.lang.String messageCode;
    protected java.lang.String messageDescription;
    protected java.lang.String policyNumber;
    protected java.lang.String institution;
    protected java.lang.String institutionCallCenter;
    protected double amountDue;
    protected boolean payAfterRegister;
    protected java.lang.String receiptReferenceNumber;
    protected com.nmt.payapi.TClientDetailPolicy clientInfo;
    
    public TRegisterPolicy() {
    }
    
    public TRegisterPolicy(java.lang.String messageCode, java.lang.String messageDescription, java.lang.String policyNumber, java.lang.String institution, java.lang.String institutionCallCenter, double amountDue, boolean payAfterRegister, java.lang.String receiptReferenceNumber, com.nmt.payapi.TClientDetailPolicy clientInfo) {
        this.messageCode = messageCode;
        this.messageDescription = messageDescription;
        this.policyNumber = policyNumber;
        this.institution = institution;
        this.institutionCallCenter = institutionCallCenter;
        this.amountDue = amountDue;
        this.payAfterRegister = payAfterRegister;
        this.receiptReferenceNumber = receiptReferenceNumber;
        this.clientInfo = clientInfo;
    }
    
    public java.lang.String getMessageCode() {
        return messageCode;
    }
    
    public void setMessageCode(java.lang.String messageCode) {
        this.messageCode = messageCode;
    }
    
    public java.lang.String getMessageDescription() {
        return messageDescription;
    }
    
    public void setMessageDescription(java.lang.String messageDescription) {
        this.messageDescription = messageDescription;
    }
    
    public java.lang.String getPolicyNumber() {
        return policyNumber;
    }
    
    public void setPolicyNumber(java.lang.String policyNumber) {
        this.policyNumber = policyNumber;
    }
    
    public java.lang.String getInstitution() {
        return institution;
    }
    
    public void setInstitution(java.lang.String institution) {
        this.institution = institution;
    }
    
    public java.lang.String getInstitutionCallCenter() {
        return institutionCallCenter;
    }
    
    public void setInstitutionCallCenter(java.lang.String institutionCallCenter) {
        this.institutionCallCenter = institutionCallCenter;
    }
    
    public double getAmountDue() {
        return amountDue;
    }
    
    public void setAmountDue(double amountDue) {
        this.amountDue = amountDue;
    }
    
    public boolean isPayAfterRegister() {
        return payAfterRegister;
    }
    
    public void setPayAfterRegister(boolean payAfterRegister) {
        this.payAfterRegister = payAfterRegister;
    }
    
    public java.lang.String getReceiptReferenceNumber() {
        return receiptReferenceNumber;
    }
    
    public void setReceiptReferenceNumber(java.lang.String receiptReferenceNumber) {
        this.receiptReferenceNumber = receiptReferenceNumber;
    }
    
    public com.nmt.payapi.TClientDetailPolicy getClientInfo() {
        return clientInfo;
    }
    
    public void setClientInfo(com.nmt.payapi.TClientDetailPolicy clientInfo) {
        this.clientInfo = clientInfo;
    }
}
