// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;


public class Webservice_CallMe_RequestStruct {
    protected java.lang.String loginID;
    protected java.lang.String password;
    protected java.lang.String contactNo;
    protected java.lang.String storeID;
    protected java.lang.String tillID;
    
    public Webservice_CallMe_RequestStruct() {
    }
    
    public Webservice_CallMe_RequestStruct(java.lang.String loginID, java.lang.String password, java.lang.String contactNo, java.lang.String storeID, java.lang.String tillID) {
        this.loginID = loginID;
        this.password = password;
        this.contactNo = contactNo;
        this.storeID = storeID;
        this.tillID = tillID;
    }
    
    public java.lang.String getLoginID() {
        return loginID;
    }
    
    public void setLoginID(java.lang.String loginID) {
        this.loginID = loginID;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public java.lang.String getContactNo() {
        return contactNo;
    }
    
    public void setContactNo(java.lang.String contactNo) {
        this.contactNo = contactNo;
    }
    
    public java.lang.String getStoreID() {
        return storeID;
    }
    
    public void setStoreID(java.lang.String storeID) {
        this.storeID = storeID;
    }
    
    public java.lang.String getTillID() {
        return tillID;
    }
    
    public void setTillID(java.lang.String tillID) {
        this.tillID = tillID;
    }
}
