// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;


public class Webservice_PayRefund_ResponseStruct {
    protected com.nmt.payapi.TPayRefund _return;
    
    public Webservice_PayRefund_ResponseStruct() {
    }
    
    public Webservice_PayRefund_ResponseStruct(com.nmt.payapi.TPayRefund _return) {
        this._return = _return;
    }
    
    public com.nmt.payapi.TPayRefund get_return() {
        return _return;
    }
    
    public void set_return(com.nmt.payapi.TPayRefund _return) {
        this._return = _return;
    }
}
