// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class Webservice_RegisterAccount_RequestStruct_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_LoginID_QNAME = new QName("", "LoginID");
    private static final javax.xml.namespace.QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer ns2_myns2_string__java_lang_String_String_Serializer;
    private static final javax.xml.namespace.QName ns1_Password_QNAME = new QName("", "Password");
    private static final javax.xml.namespace.QName ns1_AccountNumber_QNAME = new QName("", "AccountNumber");
    private static final javax.xml.namespace.QName ns1_FirstName_QNAME = new QName("", "FirstName");
    private static final javax.xml.namespace.QName ns1_LastName_QNAME = new QName("", "LastName");
    private static final javax.xml.namespace.QName ns1_IDNumber_QNAME = new QName("", "IDNumber");
    private static final javax.xml.namespace.QName ns1_ContactNumber_QNAME = new QName("", "ContactNumber");
    private static final javax.xml.namespace.QName ns1_Address_QNAME = new QName("", "Address");
    private static final javax.xml.namespace.QName ns1_TextField1_QNAME = new QName("", "TextField1");
    private static final javax.xml.namespace.QName ns1_TextField2_QNAME = new QName("", "TextField2");
    private static final javax.xml.namespace.QName ns1_TextField3_QNAME = new QName("", "TextField3");
    private static final javax.xml.namespace.QName ns1_RealTime_QNAME = new QName("", "RealTime");
    private static final javax.xml.namespace.QName ns2_boolean_TYPE_QNAME = SchemaConstants.QNAME_TYPE_BOOLEAN;
    private CombinedSerializer ns2_myns2__boolean__boolean_Boolean_Serializer;
    private static final javax.xml.namespace.QName ns1_Echo_QNAME = new QName("", "Echo");
    private static final int myLOGINID_INDEX = 0;
    private static final int myPASSWORD_INDEX = 1;
    private static final int myACCOUNTNUMBER_INDEX = 2;
    private static final int myFIRSTNAME_INDEX = 3;
    private static final int myLASTNAME_INDEX = 4;
    private static final int myIDNUMBER_INDEX = 5;
    private static final int myCONTACTNUMBER_INDEX = 6;
    private static final int myADDRESS_INDEX = 7;
    private static final int myTEXTFIELD1_INDEX = 8;
    private static final int myTEXTFIELD2_INDEX = 9;
    private static final int myTEXTFIELD3_INDEX = 10;
    private static final int myREALTIME_INDEX = 11;
    private static final int myECHO_INDEX = 12;
    
    public Webservice_RegisterAccount_RequestStruct_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws java.lang.Exception {
        ns2_myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, java.lang.String.class, ns2_string_TYPE_QNAME);
        ns2_myns2__boolean__boolean_Boolean_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, boolean.class, ns2_boolean_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        com.nmt.payapi.Webservice_RegisterAccount_RequestStruct instance = new com.nmt.payapi.Webservice_RegisterAccount_RequestStruct();
        com.nmt.payapi.Webservice_RegisterAccount_RequestStruct_SOAPBuilder builder = null;
        java.lang.Object member;
        boolean isComplete = true;
        javax.xml.namespace.QName elementName;
        
        reader.nextElementContent();
        for (int i=0; i<13; i++) {
            elementName = reader.getName();
            if (reader.getState() == XMLReader.END) {
                break;
            }
            if (elementName.equals(ns1_LoginID_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_LoginID_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_RegisterAccount_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myLOGINID_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setLoginID((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_Password_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_Password_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_RegisterAccount_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myPASSWORD_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setPassword((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_AccountNumber_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_AccountNumber_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_RegisterAccount_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myACCOUNTNUMBER_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAccountNumber((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_FirstName_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_FirstName_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_RegisterAccount_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myFIRSTNAME_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setFirstName((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_LastName_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_LastName_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_RegisterAccount_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myLASTNAME_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setLastName((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_IDNumber_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_IDNumber_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_RegisterAccount_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myIDNUMBER_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setIDNumber((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_ContactNumber_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_ContactNumber_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_RegisterAccount_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myCONTACTNUMBER_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setContactNumber((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_Address_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_Address_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_RegisterAccount_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myADDRESS_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setAddress((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_TextField1_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_TextField1_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_RegisterAccount_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myTEXTFIELD1_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setTextField1((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_TextField2_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_TextField2_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_RegisterAccount_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myTEXTFIELD2_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setTextField2((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_TextField3_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_TextField3_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_RegisterAccount_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myTEXTFIELD3_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setTextField3((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_RealTime_QNAME)) {
                member = ns2_myns2__boolean__boolean_Boolean_Serializer.deserialize(ns1_RealTime_QNAME, reader, context);
                instance.setRealTime(((Boolean)member).booleanValue());
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_Echo_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_Echo_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_RegisterAccount_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myECHO_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setEcho((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            } else {
                throw new DeserializationException("soap.unexpectedElementName", new Object[] {ns1_Echo_QNAME, elementName});
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (java.lang.Object)instance : (java.lang.Object)state);
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.nmt.payapi.Webservice_RegisterAccount_RequestStruct instance = (com.nmt.payapi.Webservice_RegisterAccount_RequestStruct)obj;
        
    }
    
    public void doSerializeInstance(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.nmt.payapi.Webservice_RegisterAccount_RequestStruct instance = (com.nmt.payapi.Webservice_RegisterAccount_RequestStruct)obj;
        
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getLoginID(), ns1_LoginID_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getPassword(), ns1_Password_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAccountNumber(), ns1_AccountNumber_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getFirstName(), ns1_FirstName_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getLastName(), ns1_LastName_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getIDNumber(), ns1_IDNumber_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getContactNumber(), ns1_ContactNumber_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAddress(), ns1_Address_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getTextField1(), ns1_TextField1_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getTextField2(), ns1_TextField2_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getTextField3(), ns1_TextField3_QNAME, null, writer, context);
        ns2_myns2__boolean__boolean_Boolean_Serializer.serialize(new Boolean(instance.isRealTime()), ns1_RealTime_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getEcho(), ns1_Echo_QNAME, null, writer, context);
    }
}
