// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class Webservice_ConfirmPayment_RequestStruct_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_LoginID_QNAME = new QName("", "LoginID");
    private static final javax.xml.namespace.QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer ns2_myns2_string__java_lang_String_String_Serializer;
    private static final javax.xml.namespace.QName ns1_Password_QNAME = new QName("", "Password");
    private static final javax.xml.namespace.QName ns1_TransactionID_QNAME = new QName("", "TransactionID");
    private static final javax.xml.namespace.QName ns1_AmountDue_QNAME = new QName("", "AmountDue");
    private static final javax.xml.namespace.QName ns2_double_TYPE_QNAME = SchemaConstants.QNAME_TYPE_DOUBLE;
    private CombinedSerializer ns2_myns2__double__double_Double_Serializer;
    private static final javax.xml.namespace.QName ns1_AdditionalAmount_QNAME = new QName("", "AdditionalAmount");
    private static final javax.xml.namespace.QName ns1_TenderType_QNAME = new QName("", "TenderType");
    private static final javax.xml.namespace.QName ns1_ConfirmationType_QNAME = new QName("", "ConfirmationType");
    private static final javax.xml.namespace.QName ns2_int_TYPE_QNAME = SchemaConstants.QNAME_TYPE_INT;
    private CombinedSerializer ns2_myns2__int__int_Int_Serializer;
    private static final javax.xml.namespace.QName ns1_Echo_QNAME = new QName("", "Echo");
    private static final javax.xml.namespace.QName ns1_CardNumber_QNAME = new QName("", "CardNumber");
    private static final javax.xml.namespace.QName ns1_CurrencyCode_QNAME = new QName("", "CurrencyCode");
    private static final int myLOGINID_INDEX = 0;
    private static final int myPASSWORD_INDEX = 1;
    private static final int myTRANSACTIONID_INDEX = 2;
    private static final int myAMOUNTDUE_INDEX = 3;
    private static final int myADDITIONALAMOUNT_INDEX = 4;
    private static final int myTENDERTYPE_INDEX = 5;
    private static final int myCONFIRMATIONTYPE_INDEX = 6;
    private static final int myECHO_INDEX = 7;
    private static final int myCARDNUMBER_INDEX = 8;
    private static final int myCURRENCYCODE_INDEX = 9;
    
    public Webservice_ConfirmPayment_RequestStruct_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws java.lang.Exception {
        ns2_myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, java.lang.String.class, ns2_string_TYPE_QNAME);
        ns2_myns2__double__double_Double_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, double.class, ns2_double_TYPE_QNAME);
        ns2_myns2__int__int_Int_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, int.class, ns2_int_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct instance = new com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct();
        com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct_SOAPBuilder builder = null;
        java.lang.Object member;
        boolean isComplete = true;
        javax.xml.namespace.QName elementName;
        
        reader.nextElementContent();
        for (int i=0; i<10; i++) {
            elementName = reader.getName();
            if (reader.getState() == XMLReader.END) {
                break;
            }
            if (elementName.equals(ns1_LoginID_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_LoginID_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myLOGINID_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setLoginID((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_Password_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_Password_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myPASSWORD_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setPassword((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_TransactionID_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_TransactionID_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myTRANSACTIONID_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setTransactionID((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_AmountDue_QNAME)) {
                member = ns2_myns2__double__double_Double_Serializer.deserialize(ns1_AmountDue_QNAME, reader, context);
                instance.setAmountDue(((Double)member).doubleValue());
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_AdditionalAmount_QNAME)) {
                member = ns2_myns2__double__double_Double_Serializer.deserialize(ns1_AdditionalAmount_QNAME, reader, context);
                instance.setAdditionalAmount(((Double)member).doubleValue());
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_TenderType_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_TenderType_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myTENDERTYPE_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setTenderType((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_ConfirmationType_QNAME)) {
                member = ns2_myns2__int__int_Int_Serializer.deserialize(ns1_ConfirmationType_QNAME, reader, context);
                instance.setConfirmationType(((java.lang.Integer)member).intValue());
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_Echo_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_Echo_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myECHO_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setEcho((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_CardNumber_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_CardNumber_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myCARDNUMBER_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setCardNumber((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_CurrencyCode_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_CurrencyCode_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myCURRENCYCODE_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setCurrencyCode((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            } else {
                throw new DeserializationException("soap.unexpectedElementName", new Object[] {ns1_CurrencyCode_QNAME, elementName});
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (java.lang.Object)instance : (java.lang.Object)state);
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct instance = (com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct)obj;
        
    }
    
    public void doSerializeInstance(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct instance = (com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct)obj;
        
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getLoginID(), ns1_LoginID_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getPassword(), ns1_Password_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getTransactionID(), ns1_TransactionID_QNAME, null, writer, context);
        ns2_myns2__double__double_Double_Serializer.serialize(new Double(instance.getAmountDue()), ns1_AmountDue_QNAME, null, writer, context);
        ns2_myns2__double__double_Double_Serializer.serialize(new Double(instance.getAdditionalAmount()), ns1_AdditionalAmount_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getTenderType(), ns1_TenderType_QNAME, null, writer, context);
        ns2_myns2__int__int_Int_Serializer.serialize(new java.lang.Integer(instance.getConfirmationType()), ns1_ConfirmationType_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getEcho(), ns1_Echo_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getCardNumber(), ns1_CardNumber_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getCurrencyCode(), ns1_CurrencyCode_QNAME, null, writer, context);
    }
}
