// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;


public class Webservice_ConfirmPayment_RequestStruct {
    protected java.lang.String loginID;
    protected java.lang.String password;
    protected java.lang.String transactionID;
    protected double amountDue;
    protected double additionalAmount;
    protected java.lang.String tenderType;
    protected int confirmationType;
    protected java.lang.String echo;
    protected java.lang.String cardNumber;
    protected java.lang.String currencyCode;
    
    public Webservice_ConfirmPayment_RequestStruct() {
    }
    
    public Webservice_ConfirmPayment_RequestStruct(java.lang.String loginID, java.lang.String password, java.lang.String transactionID, double amountDue, double additionalAmount, java.lang.String tenderType, int confirmationType, java.lang.String echo, java.lang.String cardNumber, java.lang.String currencyCode) {
        this.loginID = loginID;
        this.password = password;
        this.transactionID = transactionID;
        this.amountDue = amountDue;
        this.additionalAmount = additionalAmount;
        this.tenderType = tenderType;
        this.confirmationType = confirmationType;
        this.echo = echo;
        this.cardNumber = cardNumber;
        this.currencyCode = currencyCode;
    }
    
    public java.lang.String getLoginID() {
        return loginID;
    }
    
    public void setLoginID(java.lang.String loginID) {
        this.loginID = loginID;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public java.lang.String getTransactionID() {
        return transactionID;
    }
    
    public void setTransactionID(java.lang.String transactionID) {
        this.transactionID = transactionID;
    }
    
    public double getAmountDue() {
        return amountDue;
    }
    
    public void setAmountDue(double amountDue) {
        this.amountDue = amountDue;
    }
    
    public double getAdditionalAmount() {
        return additionalAmount;
    }
    
    public void setAdditionalAmount(double additionalAmount) {
        this.additionalAmount = additionalAmount;
    }
    
    public java.lang.String getTenderType() {
        return tenderType;
    }
    
    public void setTenderType(java.lang.String tenderType) {
        this.tenderType = tenderType;
    }
    
    public int getConfirmationType() {
        return confirmationType;
    }
    
    public void setConfirmationType(int confirmationType) {
        this.confirmationType = confirmationType;
    }
    
    public java.lang.String getEcho() {
        return echo;
    }
    
    public void setEcho(java.lang.String echo) {
        this.echo = echo;
    }
    
    public java.lang.String getCardNumber() {
        return cardNumber;
    }
    
    public void setCardNumber(java.lang.String cardNumber) {
        this.cardNumber = cardNumber;
    }
    
    public java.lang.String getCurrencyCode() {
        return currencyCode;
    }
    
    public void setCurrencyCode(java.lang.String currencyCode) {
        this.currencyCode = currencyCode;
    }
}
