// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class Webservice_ConfirmPayment_RequestStruct_SOAPBuilder implements SOAPInstanceBuilder {
    private com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct _instance;
    private java.lang.String loginID;
    private java.lang.String password;
    private java.lang.String transactionID;
    private double amountDue;
    private double additionalAmount;
    private java.lang.String tenderType;
    private int confirmationType;
    private java.lang.String echo;
    private java.lang.String cardNumber;
    private java.lang.String currencyCode;
    private static final int myLOGINID_INDEX = 0;
    private static final int myPASSWORD_INDEX = 1;
    private static final int myTRANSACTIONID_INDEX = 2;
    private static final int myAMOUNTDUE_INDEX = 3;
    private static final int myADDITIONALAMOUNT_INDEX = 4;
    private static final int myTENDERTYPE_INDEX = 5;
    private static final int myCONFIRMATIONTYPE_INDEX = 6;
    private static final int myECHO_INDEX = 7;
    private static final int myCARDNUMBER_INDEX = 8;
    private static final int myCURRENCYCODE_INDEX = 9;
    
    public Webservice_ConfirmPayment_RequestStruct_SOAPBuilder() {
    }
    
    public void setLoginID(java.lang.String loginID) {
        this.loginID = loginID;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public void setTransactionID(java.lang.String transactionID) {
        this.transactionID = transactionID;
    }
    
    public void setAmountDue(double amountDue) {
        this.amountDue = amountDue;
    }
    
    public void setAdditionalAmount(double additionalAmount) {
        this.additionalAmount = additionalAmount;
    }
    
    public void setTenderType(java.lang.String tenderType) {
        this.tenderType = tenderType;
    }
    
    public void setConfirmationType(int confirmationType) {
        this.confirmationType = confirmationType;
    }
    
    public void setEcho(java.lang.String echo) {
        this.echo = echo;
    }
    
    public void setCardNumber(java.lang.String cardNumber) {
        this.cardNumber = cardNumber;
    }
    
    public void setCurrencyCode(java.lang.String currencyCode) {
        this.currencyCode = currencyCode;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myLOGINID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myPASSWORD_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myTRANSACTIONID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myTENDERTYPE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myECHO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myCARDNUMBER_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myCURRENCYCODE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myLOGINID_INDEX:
                    _instance.setLoginID((java.lang.String)memberValue);
                    break;
                case myPASSWORD_INDEX:
                    _instance.setPassword((java.lang.String)memberValue);
                    break;
                case myTRANSACTIONID_INDEX:
                    _instance.setTransactionID((java.lang.String)memberValue);
                    break;
                case myTENDERTYPE_INDEX:
                    _instance.setTenderType((java.lang.String)memberValue);
                    break;
                case myECHO_INDEX:
                    _instance.setEcho((java.lang.String)memberValue);
                    break;
                case myCARDNUMBER_INDEX:
                    _instance.setCardNumber((java.lang.String)memberValue);
                    break;
                case myCURRENCYCODE_INDEX:
                    _instance.setCurrencyCode((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
