// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;


public class Webservice_Echo_RequestStruct {
    protected java.lang.String loginID;
    protected java.lang.String password;
    protected java.lang.String echoMessage;
    
    public Webservice_Echo_RequestStruct() {
    }
    
    public Webservice_Echo_RequestStruct(java.lang.String loginID, java.lang.String password, java.lang.String echoMessage) {
        this.loginID = loginID;
        this.password = password;
        this.echoMessage = echoMessage;
    }
    
    public java.lang.String getLoginID() {
        return loginID;
    }
    
    public void setLoginID(java.lang.String loginID) {
        this.loginID = loginID;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public java.lang.String getEchoMessage() {
        return echoMessage;
    }
    
    public void setEchoMessage(java.lang.String echoMessage) {
        this.echoMessage = echoMessage;
    }
}
