// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;


public class Webservice_RegisterAccount_RequestStruct {
    protected java.lang.String loginID;
    protected java.lang.String password;
    protected java.lang.String accountNumber;
    protected java.lang.String firstName;
    protected java.lang.String lastName;
    protected java.lang.String IDNumber;
    protected java.lang.String contactNumber;
    protected java.lang.String address;
    protected java.lang.String textField1;
    protected java.lang.String textField2;
    protected java.lang.String textField3;
    protected boolean realTime;
    protected java.lang.String echo;
    
    public Webservice_RegisterAccount_RequestStruct() {
    }
    
    public Webservice_RegisterAccount_RequestStruct(java.lang.String loginID, java.lang.String password, java.lang.String accountNumber, java.lang.String firstName, java.lang.String lastName, java.lang.String IDNumber, java.lang.String contactNumber, java.lang.String address, java.lang.String textField1, java.lang.String textField2, java.lang.String textField3, boolean realTime, java.lang.String echo) {
        this.loginID = loginID;
        this.password = password;
        this.accountNumber = accountNumber;
        this.firstName = firstName;
        this.lastName = lastName;
        this.IDNumber = IDNumber;
        this.contactNumber = contactNumber;
        this.address = address;
        this.textField1 = textField1;
        this.textField2 = textField2;
        this.textField3 = textField3;
        this.realTime = realTime;
        this.echo = echo;
    }
    
    public java.lang.String getLoginID() {
        return loginID;
    }
    
    public void setLoginID(java.lang.String loginID) {
        this.loginID = loginID;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public java.lang.String getAccountNumber() {
        return accountNumber;
    }
    
    public void setAccountNumber(java.lang.String accountNumber) {
        this.accountNumber = accountNumber;
    }
    
    public java.lang.String getFirstName() {
        return firstName;
    }
    
    public void setFirstName(java.lang.String firstName) {
        this.firstName = firstName;
    }
    
    public java.lang.String getLastName() {
        return lastName;
    }
    
    public void setLastName(java.lang.String lastName) {
        this.lastName = lastName;
    }
    
    public java.lang.String getIDNumber() {
        return IDNumber;
    }
    
    public void setIDNumber(java.lang.String IDNumber) {
        this.IDNumber = IDNumber;
    }
    
    public java.lang.String getContactNumber() {
        return contactNumber;
    }
    
    public void setContactNumber(java.lang.String contactNumber) {
        this.contactNumber = contactNumber;
    }
    
    public java.lang.String getAddress() {
        return address;
    }
    
    public void setAddress(java.lang.String address) {
        this.address = address;
    }
    
    public java.lang.String getTextField1() {
        return textField1;
    }
    
    public void setTextField1(java.lang.String textField1) {
        this.textField1 = textField1;
    }
    
    public java.lang.String getTextField2() {
        return textField2;
    }
    
    public void setTextField2(java.lang.String textField2) {
        this.textField2 = textField2;
    }
    
    public java.lang.String getTextField3() {
        return textField3;
    }
    
    public void setTextField3(java.lang.String textField3) {
        this.textField3 = textField3;
    }
    
    public boolean isRealTime() {
        return realTime;
    }
    
    public void setRealTime(boolean realTime) {
        this.realTime = realTime;
    }
    
    public java.lang.String getEcho() {
        return echo;
    }
    
    public void setEcho(java.lang.String echo) {
        this.echo = echo;
    }
}
