// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class Webservice_RegisterPolicy_RequestStruct_SOAPBuilder implements SOAPInstanceBuilder {
    private com.nmt.payapi.Webservice_RegisterPolicy_RequestStruct _instance;
    private java.lang.String loginID;
    private java.lang.String password;
    private java.lang.String policyNumber;
    private java.lang.String firstName;
    private java.lang.String lastName;
    private java.lang.String IDNumber;
    private java.lang.String contactNumber;
    private java.lang.String address;
    private java.lang.String textField1;
    private java.lang.String textField2;
    private java.lang.String textField3;
    private boolean realTime;
    private java.lang.String echo;
    private double additionalAmount;
    private java.lang.String paymentRefNumber;
    private java.lang.String storeID;
    private java.lang.String tillID;
    private java.lang.String paymentReceiptNo;
    private boolean realTimePayment;
    private boolean verifyOnly;
    private static final int myLOGINID_INDEX = 0;
    private static final int myPASSWORD_INDEX = 1;
    private static final int myPOLICYNUMBER_INDEX = 2;
    private static final int myFIRSTNAME_INDEX = 3;
    private static final int myLASTNAME_INDEX = 4;
    private static final int myIDNUMBER_INDEX = 5;
    private static final int myCONTACTNUMBER_INDEX = 6;
    private static final int myADDRESS_INDEX = 7;
    private static final int myTEXTFIELD1_INDEX = 8;
    private static final int myTEXTFIELD2_INDEX = 9;
    private static final int myTEXTFIELD3_INDEX = 10;
    private static final int myREALTIME_INDEX = 11;
    private static final int myECHO_INDEX = 12;
    private static final int myADDITIONALAMOUNT_INDEX = 13;
    private static final int myPAYMENTREFNUMBER_INDEX = 14;
    private static final int mySTOREID_INDEX = 15;
    private static final int myTILLID_INDEX = 16;
    private static final int myPAYMENTRECEIPTNO_INDEX = 17;
    private static final int myREALTIMEPAYMENT_INDEX = 18;
    private static final int myVERIFYONLY_INDEX = 19;
    
    public Webservice_RegisterPolicy_RequestStruct_SOAPBuilder() {
    }
    
    public void setLoginID(java.lang.String loginID) {
        this.loginID = loginID;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public void setPolicyNumber(java.lang.String policyNumber) {
        this.policyNumber = policyNumber;
    }
    
    public void setFirstName(java.lang.String firstName) {
        this.firstName = firstName;
    }
    
    public void setLastName(java.lang.String lastName) {
        this.lastName = lastName;
    }
    
    public void setIDNumber(java.lang.String IDNumber) {
        this.IDNumber = IDNumber;
    }
    
    public void setContactNumber(java.lang.String contactNumber) {
        this.contactNumber = contactNumber;
    }
    
    public void setAddress(java.lang.String address) {
        this.address = address;
    }
    
    public void setTextField1(java.lang.String textField1) {
        this.textField1 = textField1;
    }
    
    public void setTextField2(java.lang.String textField2) {
        this.textField2 = textField2;
    }
    
    public void setTextField3(java.lang.String textField3) {
        this.textField3 = textField3;
    }
    
    public void setRealTime(boolean realTime) {
        this.realTime = realTime;
    }
    
    public void setEcho(java.lang.String echo) {
        this.echo = echo;
    }
    
    public void setAdditionalAmount(double additionalAmount) {
        this.additionalAmount = additionalAmount;
    }
    
    public void setPaymentRefNumber(java.lang.String paymentRefNumber) {
        this.paymentRefNumber = paymentRefNumber;
    }
    
    public void setStoreID(java.lang.String storeID) {
        this.storeID = storeID;
    }
    
    public void setTillID(java.lang.String tillID) {
        this.tillID = tillID;
    }
    
    public void setPaymentReceiptNo(java.lang.String paymentReceiptNo) {
        this.paymentReceiptNo = paymentReceiptNo;
    }
    
    public void setRealTimePayment(boolean realTimePayment) {
        this.realTimePayment = realTimePayment;
    }
    
    public void setVerifyOnly(boolean verifyOnly) {
        this.verifyOnly = verifyOnly;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myLOGINID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myPASSWORD_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myPOLICYNUMBER_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myFIRSTNAME_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myLASTNAME_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myIDNUMBER_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myCONTACTNUMBER_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDRESS_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myTEXTFIELD1_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myTEXTFIELD2_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myTEXTFIELD3_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myECHO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myPAYMENTREFNUMBER_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySTOREID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myTILLID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myPAYMENTRECEIPTNO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myLOGINID_INDEX:
                    _instance.setLoginID((java.lang.String)memberValue);
                    break;
                case myPASSWORD_INDEX:
                    _instance.setPassword((java.lang.String)memberValue);
                    break;
                case myPOLICYNUMBER_INDEX:
                    _instance.setPolicyNumber((java.lang.String)memberValue);
                    break;
                case myFIRSTNAME_INDEX:
                    _instance.setFirstName((java.lang.String)memberValue);
                    break;
                case myLASTNAME_INDEX:
                    _instance.setLastName((java.lang.String)memberValue);
                    break;
                case myIDNUMBER_INDEX:
                    _instance.setIDNumber((java.lang.String)memberValue);
                    break;
                case myCONTACTNUMBER_INDEX:
                    _instance.setContactNumber((java.lang.String)memberValue);
                    break;
                case myADDRESS_INDEX:
                    _instance.setAddress((java.lang.String)memberValue);
                    break;
                case myTEXTFIELD1_INDEX:
                    _instance.setTextField1((java.lang.String)memberValue);
                    break;
                case myTEXTFIELD2_INDEX:
                    _instance.setTextField2((java.lang.String)memberValue);
                    break;
                case myTEXTFIELD3_INDEX:
                    _instance.setTextField3((java.lang.String)memberValue);
                    break;
                case myECHO_INDEX:
                    _instance.setEcho((java.lang.String)memberValue);
                    break;
                case myPAYMENTREFNUMBER_INDEX:
                    _instance.setPaymentRefNumber((java.lang.String)memberValue);
                    break;
                case mySTOREID_INDEX:
                    _instance.setStoreID((java.lang.String)memberValue);
                    break;
                case myTILLID_INDEX:
                    _instance.setTillID((java.lang.String)memberValue);
                    break;
                case myPAYMENTRECEIPTNO_INDEX:
                    _instance.setPaymentReceiptNo((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.nmt.payapi.Webservice_RegisterPolicy_RequestStruct)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
