// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package com.nmt.payapi;

import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.client.HandlerChainImpl;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;
import javax.xml.namespace.QName;
import javax.xml.rpc.JAXRPCException;

public class Webserviceservice_Impl extends com.sun.xml.rpc.client.BasicService implements Webserviceservice {

  private static final QName serviceName = new QName("http://www.finsp.co.za/", "Webserviceservice");
  private static final QName ns1_webservicePort_QNAME = new QName("http://www.finsp.co.za/", "webservicePort");
  private static final Class webservice_PortClass = com.nmt.payapi.Webservice.class;

  public Webserviceservice_Impl() {
    super(serviceName, new QName[]{
      ns1_webservicePort_QNAME
    },
            new com.nmt.payapi.Webserviceservice_SerializerRegistry().getRegistry());

  }

  public java.rmi.Remote getPort(javax.xml.namespace.QName portName, java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
    try {
      if (portName.equals(ns1_webservicePort_QNAME)
              && serviceDefInterface.equals(webservice_PortClass)) {
        return getWebservicePort();
      }
    } catch (Exception e) {
      throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
    }
    return super.getPort(portName, serviceDefInterface);
  }

  public java.rmi.Remote getPort(java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
    try {
      if (serviceDefInterface.equals(webservice_PortClass)) {
        return getWebservicePort();
      }
    } catch (Exception e) {
      throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
    }
    return super.getPort(serviceDefInterface);
  }

  public com.nmt.payapi.Webservice getWebservicePort() {
    java.lang.String[] roles = new java.lang.String[]{};
    HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_webservicePort_QNAME));
    handlerChain.setRoles(roles);
    com.nmt.payapi.Webservice_Stub stub = new com.nmt.payapi.Webservice_Stub(handlerChain);
    try {
      stub._initialize(super.internalTypeRegistry);
    } catch (JAXRPCException e) {
      throw e;
    } catch (Exception e) {
      throw new JAXRPCException(e.getMessage(), e);
    }
    return stub;
  }
}
