// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;


public class Webservice_PayRefund_RequestStruct {
    protected java.lang.String loginID;
    protected java.lang.String password;
    protected java.lang.String transactionID;
    protected java.lang.String refundReason;
    protected java.lang.String echo;
    
    public Webservice_PayRefund_RequestStruct() {
    }
    
    public Webservice_PayRefund_RequestStruct(java.lang.String loginID, java.lang.String password, java.lang.String transactionID, java.lang.String refundReason, java.lang.String echo) {
        this.loginID = loginID;
        this.password = password;
        this.transactionID = transactionID;
        this.refundReason = refundReason;
        this.echo = echo;
    }
    
    public java.lang.String getLoginID() {
        return loginID;
    }
    
    public void setLoginID(java.lang.String loginID) {
        this.loginID = loginID;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public java.lang.String getTransactionID() {
        return transactionID;
    }
    
    public void setTransactionID(java.lang.String transactionID) {
        this.transactionID = transactionID;
    }
    
    public java.lang.String getRefundReason() {
        return refundReason;
    }
    
    public void setRefundReason(java.lang.String refundReason) {
        this.refundReason = refundReason;
    }
    
    public java.lang.String getEcho() {
        return echo;
    }
    
    public void setEcho(java.lang.String echo) {
        this.echo = echo;
    }
}
