// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;


public class Webservice_PayoutAccount_RequestStruct {
    protected java.lang.String loginID;
    protected java.lang.String password;
    protected java.lang.String paymentRefNumber;
    protected java.lang.String pinCode;
    protected java.lang.String echo;
    
    public Webservice_PayoutAccount_RequestStruct() {
    }
    
    public Webservice_PayoutAccount_RequestStruct(java.lang.String loginID, java.lang.String password, java.lang.String paymentRefNumber, java.lang.String pinCode, java.lang.String echo) {
        this.loginID = loginID;
        this.password = password;
        this.paymentRefNumber = paymentRefNumber;
        this.pinCode = pinCode;
        this.echo = echo;
    }
    
    public java.lang.String getLoginID() {
        return loginID;
    }
    
    public void setLoginID(java.lang.String loginID) {
        this.loginID = loginID;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public java.lang.String getPaymentRefNumber() {
        return paymentRefNumber;
    }
    
    public void setPaymentRefNumber(java.lang.String paymentRefNumber) {
        this.paymentRefNumber = paymentRefNumber;
    }
    
    public java.lang.String getPinCode() {
        return pinCode;
    }
    
    public void setPinCode(java.lang.String pinCode) {
        this.pinCode = pinCode;
    }
    
    public java.lang.String getEcho() {
        return echo;
    }
    
    public void setEcho(java.lang.String echo) {
        this.echo = echo;
    }
}
