// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nmt.payapi;


public class Webservice_PayTrafficFine_RequestStruct {
    protected java.lang.String loginID;
    protected java.lang.String password;
    protected java.lang.String noticeNumber;
    protected boolean verifyOnly;
    protected double amountDue;
    protected java.lang.String paymentRefNumber;
    protected java.lang.String storeID;
    protected java.lang.String tillID;
    protected java.lang.String paymentReceiptNo;
    protected java.lang.String echo;
    
    public Webservice_PayTrafficFine_RequestStruct() {
    }
    
    public Webservice_PayTrafficFine_RequestStruct(java.lang.String loginID, java.lang.String password, java.lang.String noticeNumber, boolean verifyOnly, double amountDue, java.lang.String paymentRefNumber, java.lang.String storeID, java.lang.String tillID, java.lang.String paymentReceiptNo, java.lang.String echo) {
        this.loginID = loginID;
        this.password = password;
        this.noticeNumber = noticeNumber;
        this.verifyOnly = verifyOnly;
        this.amountDue = amountDue;
        this.paymentRefNumber = paymentRefNumber;
        this.storeID = storeID;
        this.tillID = tillID;
        this.paymentReceiptNo = paymentReceiptNo;
        this.echo = echo;
    }
    
    public java.lang.String getLoginID() {
        return loginID;
    }
    
    public void setLoginID(java.lang.String loginID) {
        this.loginID = loginID;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public java.lang.String getNoticeNumber() {
        return noticeNumber;
    }
    
    public void setNoticeNumber(java.lang.String noticeNumber) {
        this.noticeNumber = noticeNumber;
    }
    
    public boolean isVerifyOnly() {
        return verifyOnly;
    }
    
    public void setVerifyOnly(boolean verifyOnly) {
        this.verifyOnly = verifyOnly;
    }
    
    public double getAmountDue() {
        return amountDue;
    }
    
    public void setAmountDue(double amountDue) {
        this.amountDue = amountDue;
    }
    
    public java.lang.String getPaymentRefNumber() {
        return paymentRefNumber;
    }
    
    public void setPaymentRefNumber(java.lang.String paymentRefNumber) {
        this.paymentRefNumber = paymentRefNumber;
    }
    
    public java.lang.String getStoreID() {
        return storeID;
    }
    
    public void setStoreID(java.lang.String storeID) {
        this.storeID = storeID;
    }
    
    public java.lang.String getTillID() {
        return tillID;
    }
    
    public void setTillID(java.lang.String tillID) {
        this.tillID = tillID;
    }
    
    public java.lang.String getPaymentReceiptNo() {
        return paymentReceiptNo;
    }
    
    public void setPaymentReceiptNo(java.lang.String paymentReceiptNo) {
        this.paymentReceiptNo = paymentReceiptNo;
    }
    
    public java.lang.String getEcho() {
        return echo;
    }
    
    public void setEcho(java.lang.String echo) {
        this.echo = echo;
    }
}
