// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package com.nmt.payapi;

import com.sun.xml.rpc.client.BasicService;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import javax.xml.rpc.encoding.*;
import javax.xml.namespace.QName;

public class Webserviceservice_SerializerRegistry implements SerializerConstants {

  public Webserviceservice_SerializerRegistry() {
  }

  public TypeMappingRegistry getRegistry() {

    TypeMappingRegistry registry = BasicService.createStandardTypeMappingRegistry();
    TypeMapping mapping12 = registry.getTypeMapping(SOAP12Constants.NS_SOAP_ENCODING);
    TypeMapping mapping = registry.getTypeMapping(SOAPConstants.NS_SOAP_ENCODING);
    TypeMapping mapping2 = registry.getTypeMapping("");
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "CancelPolicyResponse");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_CancelPolicy_ResponseStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_CancelPolicy_ResponseStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "PayRefund");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_PayRefund_RequestStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_PayRefund_RequestStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "ConfirmPaymentResponse");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_ConfirmPayment_ResponseStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_ConfirmPayment_ResponseStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "UploadRecon");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_UploadRecon_RequestStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_UploadRecon_RequestStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "VoidPaymentResponse");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_VoidPayment_ResponseStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_VoidPayment_ResponseStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf", "ArrayOfClientDetailAcc");
      QName elemName = new QName("", "item");
      QName elemType = new QName("urn:WebserviceIntf", "TClientDetailAccArray");
      CombinedSerializer serializer = new ObjectArraySerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING,
              elemName, elemType, com.nmt.payapi.TClientDetailAccArray.class, 1, null, SOAPVersion.SOAP_11);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TClientDetailAccArray[].class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "PayAccount");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_PayAccount_RequestStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_PayAccount_RequestStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "PayoutAccountResponse");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_PayoutAccount_ResponseStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_PayoutAccount_ResponseStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf", "TReconResults");
      CombinedSerializer serializer = new com.nmt.payapi.TReconResults_SOAPSerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TReconResults.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "PayoutAccount");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_PayoutAccount_RequestStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_PayoutAccount_RequestStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf", "TCallMeResult");
      CombinedSerializer serializer = new com.nmt.payapi.TCallMeResult_SOAPSerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TCallMeResult.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf", "ArrayOfReconResults");
      QName elemName = new QName("", "item");
      QName elemType = new QName("urn:WebserviceIntf", "TReconResults");
      CombinedSerializer serializer = new ObjectArraySerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING,
              elemName, elemType, com.nmt.payapi.TReconResults.class, 1, null, SOAPVersion.SOAP_11);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TReconResults[].class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "PayAccountResponse");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_PayAccount_ResponseStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_PayAccount_ResponseStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf", "TClientDetailAccSubArray");
      CombinedSerializer serializer = new com.nmt.payapi.TClientDetailAccSubArray_SOAPSerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TClientDetailAccSubArray.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf", "TClientDetailAccount");
      CombinedSerializer serializer = new com.nmt.payapi.TClientDetailAccount_SOAPSerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TClientDetailAccount.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "PayRefundResponse");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_PayRefund_ResponseStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_PayRefund_ResponseStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf", "TClientDetailPolicy");
      CombinedSerializer serializer = new com.nmt.payapi.TClientDetailPolicy_SOAPSerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TClientDetailPolicy.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf", "TCancelPolicy");
      CombinedSerializer serializer = new com.nmt.payapi.TCancelPolicy_SOAPSerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TCancelPolicy.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf", "SubArrayOfClientDetailAcc");
      QName elemName = new QName("", "item");
      QName elemType = new QName("urn:WebserviceIntf", "TClientDetailAccSubArray");
      CombinedSerializer serializer = new ObjectArraySerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING,
              elemName, elemType, com.nmt.payapi.TClientDetailAccSubArray.class, 1, null, SOAPVersion.SOAP_11);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TClientDetailAccSubArray[].class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf", "TPayRefund");
      CombinedSerializer serializer = new com.nmt.payapi.TPayRefund_SOAPSerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TPayRefund.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "PayPolicy");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_PayPolicy_RequestStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_PayPolicy_RequestStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "ConfirmPayment");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_ConfirmPayment_RequestStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf", "TClientDetailAccArray");
      CombinedSerializer serializer = new com.nmt.payapi.TClientDetailAccArray_SOAPSerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TClientDetailAccArray.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "VerifyPolicyResponse");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_VerifyPolicy_ResponseStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_VerifyPolicy_ResponseStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf", "TReconUploadResult");
      CombinedSerializer serializer = new com.nmt.payapi.TReconUploadResult_SOAPSerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TReconUploadResult.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "PayPolicyResponse");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_PayPolicy_ResponseStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_PayPolicy_ResponseStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "RegisterAccount");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_RegisterAccount_RequestStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_RegisterAccount_RequestStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "PayTrafficFine");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_PayTrafficFine_RequestStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_PayTrafficFine_RequestStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "Echo");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_Echo_RequestStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_Echo_RequestStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "DownloadReconResponse");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_DownloadRecon_ResponseStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_DownloadRecon_ResponseStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "EchoResponse");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_Echo_ResponseStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_Echo_ResponseStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "RegisterPolicyResponse");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_RegisterPolicy_ResponseStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_RegisterPolicy_ResponseStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "DownloadRecon");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_DownloadRecon_RequestStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_DownloadRecon_RequestStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "PayTrafficFineResponse");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_PayTrafficFine_ResponseStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_PayTrafficFine_ResponseStruct.class, type, serializer);
    }
    {
      QName type = new QName("http://bolpaygate.com/payGate/type/", "TVoidPaymentResponse");
      CombinedSerializer serializer = new com.nmt.payapi.TVoidPaymentResponse_SOAPSerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TVoidPaymentResponse.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "VerifyPolicy");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_VerifyPolicy_RequestStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_VerifyPolicy_RequestStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "CancelPolicy");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_CancelPolicy_RequestStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_CancelPolicy_RequestStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "RegisterPolicy");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_RegisterPolicy_RequestStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_RegisterPolicy_RequestStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf", "TEchoResult");
      CombinedSerializer serializer = new com.nmt.payapi.TEchoResult_SOAPSerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TEchoResult.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "RegisterAccountResponse");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_RegisterAccount_ResponseStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_RegisterAccount_ResponseStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf", "TPayoutDetails");
      CombinedSerializer serializer = new com.nmt.payapi.TPayoutDetails_SOAPSerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TPayoutDetails.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "VoidPayment");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_VoidPayment_RequestStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_VoidPayment_RequestStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "UploadReconResponse");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_UploadRecon_ResponseStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_UploadRecon_ResponseStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "CallMeResponse");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_CallMe_ResponseStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_CallMe_ResponseStruct.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf", "TRegisterPolicy");
      CombinedSerializer serializer = new com.nmt.payapi.TRegisterPolicy_SOAPSerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TRegisterPolicy.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf", "TConfirmP");
      CombinedSerializer serializer = new com.nmt.payapi.TConfirmP_SOAPSerializer(type,
              ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.TConfirmP.class, type, serializer);
    }
    {
      QName type = new QName("urn:WebserviceIntf-Webservice", "CallMe");
      CombinedSerializer serializer = new com.nmt.payapi.Webservice_CallMe_RequestStruct_SOAPSerializer(type,
              DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
      serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
      registerSerializer(mapping, com.nmt.payapi.Webservice_CallMe_RequestStruct.class, type, serializer);
    }
    return registry;
  }

  private static void registerSerializer(TypeMapping mapping, java.lang.Class javaType, javax.xml.namespace.QName xmlType,
          Serializer ser) {
    mapping.register(javaType, xmlType, new SingletonSerializerFactory(ser),
            new SingletonDeserializerFactory((Deserializer) ser));
  }

}
